DECLARE 
    @@QUERY VARCHAR(MAX), 
    @@NOREG VARCHAR(MAX) = @P_NOREG
    ;

    
SET @@QUERY = ' 
select 
A.* ,
CONVERT(varchar(10), A.VALID_FROM, 120) AS VALID_FROM,
CONVERT(varchar(10), A.VALID_TO, 120) AS VALID_TO,
PH.NAME AS EMPLOYEE_NAME,
B.POSITION_DESC AS POSITION_DESC ,
B.GROUP_LEVEL_ID AS GROUP_LEVEL_ID,
B.LEVEL_ID AS LEVEL_ID  
FROM PDI.TB_M_ROTATION_HISTORY A
LEFT JOIN dbo.TB_M_ORG_POSITION B ON A.POSITION_ABBR=B.POSITION_ABBR 
LEFT JOIN DBO.TB_M_PROFILE_HEADER PH ON A.NOREG=PH.NOREG
	WHERE 
		1=1 AND 
        A.NOREG IN ( '+@@NOREG+' )
        ORDER BY A.NOREG ASC, A.VALID_TO DESC, A.VALID_FROM DESC, A.POSITION_PERCENT DESC
';

EXECUTE (@@QUERY)