DECLARE 
    @@QUERY VARCHAR(MAX), 
    @@NOREG VARCHAR(MAX) = @P_NOREG;

SET @@QUERY = '
SELECT
SQ.*,
C.POSITION_DESC,
SH.PERSONNEL_NAME AS APP_SH_NAME,
STAT_SH.SYSTEM_VALUE AS APP_SH_LABEL,
DPH.PERSONNEL_NAME AS APP_DPH_NAME,
STAT_DPH.SYSTEM_VALUE AS APP_DPH_LABEL,
DH.PERSONNEL_NAME AS APP_DH_NAME,
STAT_DH.SYSTEM_VALUE AS APP_DH_LABEL,
DIR.PERSONNEL_NAME AS APP_DIR_NAME,
STAT_DIR.SYSTEM_VALUE AS APP_DIR_LABEL,
HR.PERSONNEL_NAME AS APP_HR_NAME,
STAT_HR.SYSTEM_VALUE AS APP_HR_LABEL
FROM (
    SELECT
	    B.TRANSACTION_ID,
        IIF(B.TRANSACTION_ID IS NULL, A.NOREG, B.NOREG) AS NOREG,
        FORMAT(IIF(B.TRANSACTION_ID IS NULL, A.VALID_FROM, B.VALID_FROM), ''yyyy-MM-dd'') AS VALID_FROM,
        FORMAT(IIF(B.TRANSACTION_ID IS NULL, A.VALID_TO, B.VALID_TO), ''yyyy-MM-dd'') AS VALID_TO,
        IIF(B.TRANSACTION_ID IS NULL, A.DEPARTMENT_ID, B.DEPARTMENT_ID) AS DEPARTMENT_ID,
        IIF(B.TRANSACTION_ID IS NULL, A.DEPARTMENT_NAME, B.DEPARTMENT_NAME) AS DEPARTMENT_NAME,
        IIF(B.TRANSACTION_ID IS NULL, A.SECTION_ID, B.SECTION_ID) AS SECTION_ID,
        IIF(B.TRANSACTION_ID IS NULL, A.SECTION_NAME, B.SECTION_NAME) AS SECTION_NAME,
        IIF(B.TRANSACTION_ID IS NULL, A.DIVISION_ID, B.DIVISION_ID) AS DIVISION_ID,
        IIF(B.TRANSACTION_ID IS NULL, A.DIVISION_NAME, B.DIVISION_NAME) AS DIVISION_NAME,
        IIF(B.TRANSACTION_ID IS NULL, A.LINE_ID, B.LINE_ID) AS LINE_ID,
        IIF(B.TRANSACTION_ID IS NULL, A.LINE_NAME, B.LINE_NAME) AS LINE_NAME,
        IIF(B.TRANSACTION_ID IS NULL, A.GROUP_ID, B.GROUP_ID) AS GROUP_ID,
        IIF(B.TRANSACTION_ID IS NULL, A.GROUP_NAME, B.GROUP_NAME) AS GROUP_NAME,
        IIF(B.TRANSACTION_ID IS NULL, A.CLASS, B.CLASS) AS CLASS,
        IIF(B.TRANSACTION_ID IS NULL, A.POSITION_PERCENT, B.POSITION_PERCENT) AS POSITION_PERCENT,
        IIF(B.TRANSACTION_ID IS NULL, A.POSITION_LEVEL, B.POSITION_LEVEL) AS POSITION_LEVEL,
        IIF(B.TRANSACTION_ID IS NULL, A.RESPONSIBILITY, B.RESPONSIBILITY) AS RESPONSIBILITY,
        IIF(B.TRANSACTION_ID IS NULL, A.ACCOMPLISHMENT, B.ACCOMPLISHMENT) AS ACCOMPLISHMENT,
        IIF(B.TRANSACTION_ID IS NULL, A.ORG_ID, B.ORG_ID) AS ORG_ID,
        B.STATUS_CD,
        B.REJECT_REASON,
        B.APP_SH_NOREG,
        B.APP_SH_STATUS,
        B.APP_SH_DATE,
        B.APP_DPH_NOREG,
        B.APP_DPH_STATUS,
        B.APP_DPH_DATE,
        B.APP_DH_NOREG,
        B.APP_DH_STATUS,
        B.APP_DH_DATE,
        B.APP_DIR_NOREG,
        B.APP_DIR_STATUS,
        B.APP_DIR_DATE,
        B.APP_HR_ADMIN_NOREG,
        B.APP_HR_ADMIN_STATUS,
        B.APP_HR_ADMIN_DATE,
        B.CANCEL_FLAG,
        B.CANCEL_BY,
        B.CANCEL_DATE,
        A.REMARK_1 AS REMARK_1,
        A.REMARK_2 AS REMARK_2
    FROM PDI.TB_M_ROTATION_HISTORY A
    LEFT JOIN PDI.TB_R_SUBMISSION_ROTATION_HISTORY B ON A.NOREG = B.NOREG AND A.CLASS = B.CLASS AND A.POSITION_LEVEL = B.POSITION_LEVEL 
        AND A.ORG_ID = B.ORG_ID AND A.VALID_FROM = B.VALID_FROM AND A.VALID_TO = B.VALID_TO AND B.CANCEL_FLAG IS NULL AND B.STATUS_CD != ''99''
    WHERE A.NOREG = '''+@@NOREG+'''
    UNION
    SELECT
		B.TRANSACTION_ID,
        B.NOREG,
        FORMAT(B.VALID_FROM, ''yyyy-MM-dd'') AS VALID_FROM,
        FORMAT(B.VALID_TO, ''yyyy-MM-dd'') AS VALID_TO,
        B.DEPARTMENT_ID,
        B.DEPARTMENT_NAME,
        B.SECTION_ID,
        B.SECTION_NAME,
        B.DIVISION_ID,
        B.DIVISION_NAME,
        B.LINE_ID,
        B.LINE_NAME,
        B.GROUP_ID,
        B.GROUP_NAME,
        B.CLASS,
        B.POSITION_PERCENT,
        B.POSITION_LEVEL,
        B.RESPONSIBILITY,
        B.ACCOMPLISHMENT,
        B.ORG_ID,
        B.STATUS_CD,
        B.REJECT_REASON,
        B.APP_SH_NOREG,
        B.APP_SH_STATUS,
        B.APP_SH_DATE,
        B.APP_DPH_NOREG,
        B.APP_DPH_STATUS,
        B.APP_DPH_DATE,
        B.APP_DH_NOREG,
        B.APP_DH_STATUS,
        B.APP_DH_DATE,
        B.APP_DIR_NOREG,
        B.APP_DIR_STATUS,
        B.APP_DIR_DATE,
        B.APP_HR_ADMIN_NOREG,
        B.APP_HR_ADMIN_STATUS,
        B.APP_HR_ADMIN_DATE,
        B.CANCEL_FLAG,
        B.CANCEL_BY,
        B.CANCEL_DATE,
        NULL AS REMARK_1,
        NULL AS REMARK_2
    FROM PDI.TB_R_SUBMISSION_ROTATION_HISTORY B
    WHERE B.NOREG = '''+@@NOREG+'''
    AND B.CANCEL_FLAG IS NULL
    AND B.STATUS_CD != 99
) SQ
LEFT JOIN DBO.TB_M_ORG_POSITION C ON C.POSITION_LEVEL = SQ.POSITION_LEVEL
LEFT JOIN (SELECT DISTINCT(SUB_A.NOREG), SUB_A.PERSONNEL_NAME from VW_ORGANIZATION SUB_A) SH ON SH.NOREG = SQ.APP_SH_NOREG AND SQ.APP_SH_NOREG IS NOT NULL 
LEFT JOIN (SELECT DISTINCT(SUB_A.NOREG), SUB_A.PERSONNEL_NAME from VW_ORGANIZATION SUB_A) DPH ON DPH.NOREG=SQ.APP_DPH_NOREG AND SQ.APP_DPH_NOREG IS NOT NULL 
LEFT JOIN (SELECT DISTINCT(SUB_A.NOREG), SUB_A.PERSONNEL_NAME from VW_ORGANIZATION SUB_A) DH ON DH.NOREG=SQ.APP_DH_NOREG AND SQ.APP_DH_NOREG IS NOT NULL 
LEFT JOIN (SELECT DISTINCT(SUB_A.NOREG), SUB_A.PERSONNEL_NAME from VW_ORGANIZATION SUB_A) DIR ON DIR.NOREG=SQ.APP_DIR_NOREG AND SQ.APP_DIR_NOREG IS NOT NULL 
LEFT JOIN (SELECT DISTINCT(SUB_A.NOREG), SUB_A.PERSONNEL_NAME from VW_ORGANIZATION SUB_A) HR ON HR.NOREG=SQ.APP_HR_ADMIN_NOREG AND SQ.APP_HR_ADMIN_NOREG IS NOT NULL
LEFT JOIN dbo.TB_M_SYSTEM STAT_SH ON SQ.APP_SH_STATUS IS NOT NULL AND STAT_SH.FUNCTION_ID=''STATUS_APPROVAL_PDI'' AND SQ.APP_SH_STATUS = STAT_SH.SYSTEM_CD
LEFT JOIN dbo.TB_M_SYSTEM STAT_DPH ON SQ.APP_DPH_STATUS IS NOT NULL AND STAT_DPH.FUNCTION_ID=''STATUS_APPROVAL_PDI'' AND SQ.APP_DPH_STATUS = STAT_DPH.SYSTEM_CD
LEFT JOIN dbo.TB_M_SYSTEM STAT_DH ON SQ.APP_DH_STATUS IS NOT NULL AND STAT_DH.FUNCTION_ID=''STATUS_APPROVAL_PDI'' AND SQ.APP_DH_STATUS = STAT_DH.SYSTEM_CD
LEFT JOIN dbo.TB_M_SYSTEM STAT_DIR ON SQ.APP_DIR_STATUS IS NOT NULL AND STAT_DIR.FUNCTION_ID=''STATUS_APPROVAL_PDI'' AND SQ.APP_DIR_STATUS = STAT_DIR.SYSTEM_CD
LEFT JOIN dbo.TB_M_SYSTEM STAT_HR ON SQ.APP_HR_ADMIN_STATUS IS NOT NULL AND STAT_HR.FUNCTION_ID=''STATUS_APPROVAL_PDI'' AND SQ.APP_HR_ADMIN_STATUS = STAT_HR.SYSTEM_CD
WHERE 
        1=1
    AND
        SQ.NOREG = '''+@@NOREG+'''
ORDER BY SQ.NOREG ASC, SQ.VALID_TO DESC, SQ.VALID_FROM DESC, SQ.POSITION_PERCENT DESC
';

EXECUTE (@@QUERY)