DECLARE 
    @@QUERY VARCHAR(MAX) ,
    @@CONDITION VARCHAR(MAX) = @P_EDUCATION_DESC;

SET @@QUERY = 'SELECT * FROM PDI.TB_M_EDUCATION WHERE 1=1 ';

IF(@@CONDITION != '') BEGIN 
    SET @@QUERY = @@QUERY + ' AND EDUCATION_DESC LIKE ''%'+@@CONDITION+'%'' ';
END;

--

-- SELECT @@QUERY;

 EXECUTE (@@QUERY);