DECLARE 
    @@QUERY VARCHAR(MAX), 
    @@NOREG VARCHAR(MAX) = @P_NOREG,
    @@BASE_URL VARCHAR(MAX);

SET  @@BASE_URL = (
    SELECT SYSTEM_VALUE
    from DBO.TB_M_SYSTEM
    WHERE 
    FUNCTION_ID = 'ENVIRONMENT_PDI' 
    AND SYSTEM_CD = 'URL_BACKEND'	
);

SET @@QUERY = ' 
SELECT
        SQ.*,
        C.EDUCATION_DESC,
        C.EDUCATION_LEVEL,
        D.MAJOR_NAME,
        E.COUNTRY_NAME,
        SH.PERSONNEL_NAME AS APP_SH_NAME,
        STAT_SH.SYSTEM_VALUE AS APP_SH_LABEL,
        DPH.PERSONNEL_NAME AS APP_DPH_NAME,
        STAT_DPH.SYSTEM_VALUE AS APP_DPH_LABEL,
        DH.PERSONNEL_NAME AS APP_DH_NAME,
        STAT_DH.SYSTEM_VALUE AS APP_DH_LABEL,
        DIR.PERSONNEL_NAME AS APP_DIR_NAME,
        STAT_DIR.SYSTEM_VALUE AS APP_DIR_LABEL,
        HR.PERSONNEL_NAME AS APP_HR_NAME,
        STAT_HR.SYSTEM_VALUE AS APP_HR_LABEL
        FROM (
            SELECT
		        B.TRANSACTION_ID,
                IIF(B.TRANSACTION_ID IS NULL, A.NOREG, B.NOREG) AS NOREG,
                IIF(B.TRANSACTION_ID IS NULL, A.EDUCATION_CD, B.EDUCATION_CD) AS EDUCATION_CD,
                IIF(B.TRANSACTION_ID IS NULL, A.MAJOR_CD, B.MAJOR_CD) AS MAJOR_CD,
                IIF(B.TRANSACTION_ID IS NULL, A.VALID_FROM, B.VALID_FROM) AS VALID_FROM,
                IIF(B.TRANSACTION_ID IS NULL, A.VALID_TO, B.VALID_TO) AS VALID_TO,
                IIF(B.TRANSACTION_ID IS NULL, A.GPA, B.GPA) AS GPA,
                IIF(B.TRANSACTION_ID IS NULL, A.SCHOOL_NAME, B.SCHOOL_NAME) AS SCHOOL_NAME,
                IIF(B.TRANSACTION_ID IS NULL, A.CERTIFICATE_NAME, B.CERTIFICATE_NAME) AS CERTIFICATE_NAME,
                IIF(B.TRANSACTION_ID IS NULL, CONCAT('''+@@BASE_URL+''', A.CERTIFICATE_PATH), CONCAT('''+@@BASE_URL+''', B.CERTIFICATE_PATH)) AS CERTIFICATE_PATH,
                IIF(B.TRANSACTION_ID IS NULL, A.COUNTRY_ID, B.COUNTRY_ID) AS COUNTRY_ID,
                IIF(B.TRANSACTION_ID IS NULL, A.REMARK_1, B.REMARK_1) AS REMARK_1,
                B.STATUS_CD,
                B.REJECT_REASON,
                B.APP_SH_NOREG,
                B.APP_SH_STATUS,
                B.APP_SH_DATE,
                B.APP_DPH_NOREG,
                B.APP_DPH_STATUS,
                B.APP_DPH_DATE,
                B.APP_DH_NOREG,
                B.APP_DH_STATUS,
                B.APP_DH_DATE,
                B.APP_DIR_NOREG,
                B.APP_DIR_STATUS,
                B.APP_DIR_DATE,
                B.APP_HR_ADMIN_NOREG,
                B.APP_HR_ADMIN_STATUS,
                B.APP_HR_ADMIN_DATE,
                B.CANCEL_FLAG,
                B.CANCEL_BY,
                B.CANCEL_DATE
            FROM PDI.TB_M_PROFILE_EDUCATION A
            LEFT JOIN PDI.TB_R_SUBMISSION_EDUCATION B 
                ON A.NOREG = B.NOREG 
                AND A.EDUCATION_CD = B.EDUCATION_CD 
                AND A.MAJOR_CD = B.MAJOR_CD 
                AND B.CANCEL_FLAG IS NULL 
                AND B.STATUS_CD != ''99''
            WHERE A.NOREG = '''+@@NOREG+'''
            UNION
            SELECT
		        B.TRANSACTION_ID,
                B.NOREG,
                B.EDUCATION_CD,
                B.MAJOR_CD,
                B.VALID_FROM,
                B.VALID_TO,
                B.GPA,
                B.SCHOOL_NAME,
                B.CERTIFICATE_NAME,
                CONCAT('''+@@BASE_URL+''', B.CERTIFICATE_PATH) AS CERTIFICATE_PATH,
                B.COUNTRY_ID,
                B.REMARK_1,
                B.STATUS_CD,
                B.REJECT_REASON,
                B.APP_SH_NOREG,
                B.APP_SH_STATUS,
                B.APP_SH_DATE,
                B.APP_DPH_NOREG,
                B.APP_DPH_STATUS,
                B.APP_DPH_DATE,
                B.APP_DH_NOREG,
                B.APP_DH_STATUS,
                B.APP_DH_DATE,
                B.APP_DIR_NOREG,
                B.APP_DIR_STATUS,
                B.APP_DIR_DATE,
                B.APP_HR_ADMIN_NOREG,
                B.APP_HR_ADMIN_STATUS,
                B.APP_HR_ADMIN_DATE,
                B.CANCEL_FLAG,
                B.CANCEL_BY,
                B.CANCEL_DATE
            FROM PDI.TB_R_SUBMISSION_EDUCATION B
            WHERE B.NOREG = '''+@@NOREG+'''
            AND B.CANCEL_FLAG IS NULL
            AND B.STATUS_CD != 99
        ) SQ
        LEFT JOIN DBO.TB_M_EDUCATION C ON SQ.EDUCATION_CD=C.EDUCATION_CD
        LEFT JOIN DBO.TB_M_EDUCATION_MAJOR D ON SQ.EDUCATION_CD=D.EDUCATION_CD AND SQ.MAJOR_CD=D.MAJOR_CD
        LEFT JOIN DBO.TB_M_COUNTRY E ON SQ.COUNTRY_ID=E.COUNTRY_CD
        LEFT JOIN (SELECT DISTINCT(SUB_A.NOREG), SUB_A.PERSONNEL_NAME from VW_ORGANIZATION SUB_A) SH ON SH.NOREG = SQ.APP_SH_NOREG AND SQ.APP_SH_NOREG IS NOT NULL 
        LEFT JOIN (SELECT DISTINCT(SUB_A.NOREG), SUB_A.PERSONNEL_NAME from VW_ORGANIZATION SUB_A) DPH ON DPH.NOREG=SQ.APP_DPH_NOREG AND SQ.APP_DPH_NOREG IS NOT NULL 
        LEFT JOIN (SELECT DISTINCT(SUB_A.NOREG), SUB_A.PERSONNEL_NAME from VW_ORGANIZATION SUB_A) DH ON DH.NOREG=SQ.APP_DH_NOREG AND SQ.APP_DH_NOREG IS NOT NULL 
        LEFT JOIN (SELECT DISTINCT(SUB_A.NOREG), SUB_A.PERSONNEL_NAME from VW_ORGANIZATION SUB_A) DIR ON DIR.NOREG=SQ.APP_DIR_NOREG AND SQ.APP_DIR_NOREG IS NOT NULL 
        LEFT JOIN (SELECT DISTINCT(SUB_A.NOREG), SUB_A.PERSONNEL_NAME from VW_ORGANIZATION SUB_A) HR ON HR.NOREG=SQ.APP_HR_ADMIN_NOREG AND SQ.APP_HR_ADMIN_NOREG IS NOT NULL
        LEFT JOIN dbo.TB_M_SYSTEM STAT_SH ON SQ.APP_SH_STATUS IS NOT NULL AND STAT_SH.FUNCTION_ID=''STATUS_APPROVAL_PDI'' AND SQ.APP_SH_STATUS = STAT_SH.SYSTEM_CD
        LEFT JOIN dbo.TB_M_SYSTEM STAT_DPH ON SQ.APP_DPH_STATUS IS NOT NULL AND STAT_DPH.FUNCTION_ID=''STATUS_APPROVAL_PDI'' AND SQ.APP_DPH_STATUS = STAT_DPH.SYSTEM_CD
        LEFT JOIN dbo.TB_M_SYSTEM STAT_DH ON SQ.APP_DH_STATUS IS NOT NULL AND STAT_DH.FUNCTION_ID=''STATUS_APPROVAL_PDI'' AND SQ.APP_DH_STATUS = STAT_DH.SYSTEM_CD
        LEFT JOIN dbo.TB_M_SYSTEM STAT_DIR ON SQ.APP_DIR_STATUS IS NOT NULL AND STAT_DIR.FUNCTION_ID=''STATUS_APPROVAL_PDI'' AND SQ.APP_DIR_STATUS = STAT_DIR.SYSTEM_CD
        LEFT JOIN dbo.TB_M_SYSTEM STAT_HR ON SQ.APP_HR_ADMIN_STATUS IS NOT NULL AND STAT_HR.FUNCTION_ID=''STATUS_APPROVAL_PDI'' AND SQ.APP_HR_ADMIN_STATUS = STAT_HR.SYSTEM_CD
    WHERE 
        1=1
    ORDER BY SQ.VALID_TO DESC
';

EXECUTE (@@QUERY);


