DECLARE 
    @@QUERY VARCHAR(MAX), 
    @@NOREG VARCHAR(MAX) = @P_NOREG,
    @@BASE_URL VARCHAR(MAX);

SET  @@BASE_URL = (
    SELECT SYSTEM_VALUE
    from DBO.TB_M_SYSTEM
    WHERE 
    FUNCTION_ID = 'ENVIRONMENT_PDI' 
    AND SYSTEM_CD = 'URL_BACKEND'	
);
 
SET @@QUERY = '
    SELECT
        A.NOREG,
        A.EDUCATION_CD,
            PH.NAME AS EMPLOYEE_NAME,
        A.MAJOR_CD,
        A.VALID_FROM,
        A.VALID_TO,
        A.GPA,
        A.SCHOOL_NAME,
        A.CERTIFICATE_NAME,
        CONCAT('''+@@BASE_URL+''', A.CERTIFICATE_PATH) AS CERTIFICATE_PATH,
        A.COUNTRY_ID,
        A.REMARK_1,
        C.EDUCATION_DESC,
        C.EDUCATION_LEVEL,
        D.MAJOR_NAME,
        E.COUNTRY_NAME
    FROM PDI.TB_M_PROFILE_EDUCATION A
    LEFT JOIN DBO.TB_M_EDUCATION C ON A.EDUCATION_CD=C.EDUCATION_CD
    LEFT JOIN DBO.TB_M_EDUCATION_MAJOR D ON A.EDUCATION_CD=D.EDUCATION_CD AND A.MAJOR_CD=D.MAJOR_CD
    LEFT JOIN DBO.TB_M_COUNTRY E ON A.COUNTRY_ID=E.COUNTRY_CD
    LEFT JOIN DBO.TB_M_PROFILE_HEADER PH ON A.NOREG=PH.NOREG
    WHERE A.NOREG IN ( '+@@NOREG+' ) 
    ORDER BY A.NOREG ASC, A.VALID_TO DESC  
';

EXECUTE (@@QUERY);