DECLARE  
    @@QUERY VARCHAR(MAX),
    @@SUPERIOR VARCHAR(MAX),
    @@NOREG VARCHAR(MAX) = @P_NOREG,
    @@ORDER_TYPE VARCHAR(MAX) = REPLACE(@P_ORDER_TYPE, '''', '`'), 
    @@NOREG_TEMP VARCHAR(MAX),
    @@CALL_SP VARCHAR(MAX);  

SET @@QUERY = ' 
 	select 
 		DISTINCT A.NOREG, 
 		C.NAME AS PERSONNEL_NAME, 
 		B.DATE_OF_BIRTH,  
 		A.CLASS, 
 		LTRIM(RTRIM(C.POSITION)) AS POSITION, 
 		LTRIM(RTRIM(C.DIVISION)) AS DIVISION,
        C.DEPARTMENT,
        C.SECTION,
        C.LINE,
        C.[GROUP] AS "GROUP",
 		CONVERT(varchar(10), B.VALID_FROM, 120) AS JOIN_BY, 
 		B.VALID_FROM, 
        A.MAIL 
 	FROM DBO.vw_organization A
 	JOIN DBO.TB_M_PROFILE_MAIN B ON A.NOREG = B.NOREG AND GETDATE() BETWEEN B.VALID_FROM AND B.VALID_TO
 	JOIN DBO.TB_M_PROFILE_HEADER C ON A.NOREG = C.NOREG
 	JOIN DBO.TB_M_GENDER D ON B.GENDER = D.GENDER_ID
 	LEFT JOIN DBO.TB_M_PROFILE_ADDRESS E ON A.NOREG = E.NOREG AND E.ADDRESS_TYPE = 1 AND 
 		GETDATE() BETWEEN E.VALID_FROM AND E.VALID_TO
 	WHERE 
 		1 = 1 AND B.NOREG IN ('+@@NOREG+')   
        ORDER BY A.NOREG ASC, B.VALID_FROM DESC
';



EXECUTE (@@QUERY);     -- Execute the query on ##PERSONAL_DATA table
-- get user profile


