
DECLARE 
    @@QUERY VARCHAR(MAX), 
    @@NOREG VARCHAR(MAX) = @P_NOREG,
	@@URL VARCHAR(MAX) = ''; 

SET @@URL = (
SELECT SYSTEM_VALUE
from DBO.TB_M_SYSTEM
WHERE 
FUNCTION_ID = 'ENVIRONMENT_PDI'
AND SYSTEM_CD = 'URL_LINK')

SET @@QUERY = ' 
SELECT 
    A.NOREG
    , A.USERNAME
    , A.PERSONNEL_NAME      
    , A.VALID_FROM
    , A.VALID_TO
    , B.POSITION
    , B.PHOTO_DIRECTORY
    , B.PHOTO_FILENAME
    , CONCAT('''+@@URL+''', B.PHOTO_DIRECTORY, B.PHOTO_FILENAME) AS PHOTO 
    , C.DESCRIPTION 
FROM [DBO].[vw_Organization] A
LEFT JOIN DBO.TB_M_PROFILE_HEADER B ON B.NOREG=A.NOREG
LEFT JOIN PDI.TB_M_PROFILE_DESCRIPTION C on C.NOREG=A.NOREG 
WHERE 1=1 
';

SET  @@QUERY = @@QUERY +'AND A.NOREG='''+ @@NOREG+''' ';

EXECUTE (@@QUERY);