DECLARE @@sqlstate varchar(max), @@USERNAME varchar(max)
, @@FULLNAME varchar(max), @@REGNO varchar(max), @@CNT_USER INT
, @@COMPANY_ID INT, @@PLANT_CD VARCHAR(MAX), @@SHIFT_CD VARCHAR(MAX), @@ROLE_ID INT, @@JWT_TOKEN VARCHAR(MAX)

SET @@USERNAME = @pUser;
SET @@FULLNAME = @pFullname;
SET @@REGNO = @pRegno;
SET @@JWT_TOKEN = @pToken;

BEGIN TRY

	SELECT @@COMPANY_ID = SYSTEM_VALUE FROM TB_M_SYSTEM WHERE SYSTEM_TYPE = 'DEFAULT_USER' AND SYSTEM_CD = 'COMP_ID';
	SELECT @@PLANT_CD = SYSTEM_VALUE FROM TB_M_SYSTEM WHERE SYSTEM_TYPE = 'DEFAULT_USER' AND SYSTEM_CD = 'PLANT_CD';
	SELECT @@SHIFT_CD = SYSTEM_VALUE FROM TB_M_SYSTEM WHERE SYSTEM_TYPE = 'DEFAULT_USER' AND SYSTEM_CD = 'SHIFT_CD';
	SELECT @@ROLE_ID = SYSTEM_VALUE FROM TB_M_SYSTEM WHERE SYSTEM_TYPE = 'DEFAULT_USER' AND SYSTEM_CD = 'ROLE_ID';
	SELECT @@CNT_USER = COUNT(1) FROM TB_M_USER WHERE USERNAME = @@USERNAME;

	IF(@@CNT_USER = 0) BEGIN
		INSERT INTO [dbo].[TB_M_USER] (
		[COMPANY_ID], [PLANT_CD], [USERNAME], [NOREG], [NAME], [SHIFT_CD], [ROLE_ID], [JWT_TOKEN], [USER_TYPE],[CREATED_BY], [CREATED_DT]
		) 
		SELECT @@COMPANY_ID, @@PLANT_CD, @@USERNAME, @@REGNO, @@FULLNAME, @@SHIFT_CD, @@ROLE_ID, @@JWT_TOKEN, 'NON_OPERATOR', 'SYSTEM', GETDATE();
	END
	ELSE BEGIN
		UPDATE TB_M_USER SET JWT_TOKEN = @@JWT_TOKEN WHERE USERNAME = @@USERNAME;
	END

	SELECT 'true' AS result;
END TRY
BEGIN CATCH
	SELECT 'false' AS result;
END CATCH