DECLARE @@Date VARCHAR(30) = COALESCE(@DATE, FORMAT(GETDATE(), 'dd.MM.yyyy'));
DECLARE @@USERNAME VARCHAR(50) = @USERNAME;
DECLARE @@Time AS VARCHAR(30) = COALESCE((SELECT TOP 1 SYSTEM_VALUE FROM TB_M_SYSTEM WHERE SYSTEM_TYPE = 'CREATED_DT_INTERVAL'), '07:00');

DECLARE @@_PLANT_CD as varchar(max);
DECLARE @@_COMPANY_ID  as varchar(max);
SELECT @@_PLANT_CD = PLANT_CD, @@_COMPANY_ID = COMPANY_ID FROM TB_M_USER WHERE [USERNAME] = @@USERNAME;

-- Convert the date string to a datetime value with the desired format
DECLARE @@FormattedDate DATETIME = CONVERT(DATETIME, @@Date, 104); -- 104 format represents 'DD.MM.YYYY'

-- Calculate the combined datetime value
DECLARE @@START_DATETIME DATETIME = DATEADD(HOUR, DATEPART(HOUR, @@Time), DATEADD(MINUTE, DATEPART(MINUTE, @@Time), @@FormattedDate));
DECLARE @@END_DATETIME DATETIME = DATEADD(DAY, 1, @@START_DATETIME);

SELECT 
	COUNT(1) AS TOTAL,
	SUM(CASE WHEN QCG.FINAL_JUDGEMENT = 1 THEN 1 ELSE 0 END) AS OK,
	SUM(CASE WHEN QCG.FINAL_JUDGEMENT = 2 THEN 1 ELSE 0 END) AS NG,
	SUM(CASE WHEN QCG.FINAL_JUDGEMENT = 3 THEN 1 ELSE 0 END) AS REPAIR,
	SUM(CASE WHEN QCG.FINAL_JUDGEMENT = 4 THEN 1 ELSE 0 END) AS WAIT_FOR_JUDGEMENT, 
	QCG.QC_GATE2_MP_SHIFT, 
	QCG.PRODUCT_TYPE FROM TB_R_QC_GATE QCG
	WHERE QCG.CREATED_DT BETWEEN @@START_DATETIME AND @@END_DATETIME
	AND QCG.COMPANY_ID = @@_COMPANY_ID AND PLANT_CD = @@_PLANT_CD
	GROUP BY PRODUCT_TYPE, QC_GATE2_MP_SHIFT
	ORDER BY QCG.QC_GATE2_MP_SHIFT ASC