DECLARE @@QUERY VARCHAR(MAX)
, @@APPALIAS VARCHAR(50) = @P_APPALIAS
, @@ROLE VARCHAR(50) = @P_ROLE

SET @@QUERY = '
		SELECT 
			A.USERNAME as id,
			CONCAT(B.FIRST_NAME, '' '', B.LAST_NAME) as text,
			CONCAT(B.FIRST_NAME, '' '', B.LAST_NAME) as attr_1
		FROM 
			TB_M_USER_APPLICATION A
		INNER JOIN TB_M_USER B ON A.USERNAME = B.USERNAME
		WHERE APPLICATION='''+@@APPALIAS+'''
		AND A.USERNAME NOT IN (
		SELECT DISTINCT USERNAME 
		FROM TB_M_AUTHORIZATION 
		WHERE APPLICATION ='''+@@APPALIAS+''' AND ROLE LIKE ''%'+@@ROLE+'%''
		)';

EXEC(@@QUERY);