DECLARE @@QUERY VARCHAR(MAX)
, @@APPALIAS VARCHAR(50) = @P_APPALIAS
, @@ROLE VARCHAR(50) = @P_ROLE
, @@FUNCTION VARCHAR(50) = @P_FUNCTION

SET @@QUERY = '
		SELECT 
			ID as id,
			ID as text,
			NAME as attr_1
		FROM 
			TB_M_FEATURE
		WHERE APPLICATION='''+@@APPALIAS+'''
		AND ID NOT IN (
		SELECT DISTINCT FEATURE
		FROM TB_M_AUTHORIZATION 
		WHERE APPLICATION ='''+@@APPALIAS+'''
		AND ROLE ='''+@@ROLE+'''
		AND [FUNCTION] ='''+@@FUNCTION+'''
		)';

EXEC(@@QUERY);