DECLARE 
	  @@QUERY VARCHAR(MAX)
	, @@LENGTH INT = @P_LENGTH
	, @@NAME VARCHAR(50) = REPLACE(@P_NAME, '''', '`')
	, @@TYPE VARCHAR(50) = REPLACE(@P_TYPE, '''', '`')
	, @@DESCRIPTION VARCHAR(50) = REPLACE(@P_DESCRIPTION, '''', '`')
	, @@FROMNUMBER INT = @P_FROMNUMBER
	, @@TONUMBER INT = @P_TONUMBER
	, @@ORDER_BY VARCHAR(MAX) = @P_ORDER_BY
	, @@ORDER_TYPE VARCHAR(MAX) = REPLACE(@P_ORDER_TYPE, '''', '`');

SET @@QUERY = 'SELECT
	ID,
	NAME,
	TYPE,
	RUNTIME,
	DESCRIPTION
FROM TB_M_APPLICATION 
WHERE 1=1 ';


IF (@@NAME != '') BEGIN
	SET @@QUERY = @@QUERY + ' AND NAME LIKE ''%' + @@NAME + '%''';
END

IF (@@TYPE != '') BEGIN
	SET @@QUERY = @@QUERY + ' AND TYPE LIKE ''%' + @@TYPE + '%''';
END

IF (@@DESCRIPTION != '') BEGIN
	SET @@QUERY = @@QUERY + ' AND DESCRIPTION LIKE ''%' + @@DESCRIPTION + '%''';
END


IF (@@LENGTH > 0) BEGIN
	SET @@QUERY = @@QUERY +  ' ORDER BY '+ @@ORDER_BY+ ' '+@@ORDER_TYPE+ ' OFFSET ' + CONVERT(VARCHAR, @@FROMNUMBER) + ' ROWS FETCH NEXT ' + CONVERT(VARCHAR, @@LENGTH) + ' ROWS ONLY';
END

EXECUTE (@@QUERY);