DECLARE 
    @@QUERY VARCHAR(MAX), 
    @@QUERY_REQ VARCHAR(MAX), 
    @@NOREG VARCHAR(MAX) = @P_NOREG,
    @@ORDER_TYPE VARCHAR(MAX) = REPLACE(@P_ORDER_TYPE, '''', '`'), 
    @@REQ_STATUS VARCHAR(MAX) = @P_STATUS; 

DECLARE @@BASE_URL VARCHAR(MAX) = @P_URL;

SET @@QUERY = '
SELECT 
    B.NOREG ,
    B.EDUCATION_CD ,
    B.MAJOR_CD ,
    B.VALID_FROM ,
    B.VALID_TO ,
    B.GPA ,
    B.SCHOOL_NAME ,
    B.CERTIFICATE_NAME , 
    CONCAT('''+@@BASE_URL+''', B.CERTIFICATE_PATH) AS CERTIFICATE_PATH ,
    B.COUNTRY_ID ,
    B.REMARK_1 ,
    B.REMARK_2
FROM PDI.TB_M_PROFILE_EDUCATION B
WHERE 1=1 AND B.NOREG = '''+@@NOREG+'''
'; 
 

IF (@@REQ_STATUS != '') BEGIN
    SET @@QUERY = @@QUERY + ' -- and NOREG='''+@@NOREG+''' ';
END; 

EXECUTE (@@QUERY);


