DECLARE 
    @@QUERY VARCHAR(MAX), 
    @@QUERY_REQ VARCHAR(MAX),
    @@QUERY_CTE VARCHAR(MAX),
    @@NOREG VARCHAR(MAX) = @P_NOREG,
    @@ORDER_TYPE VARCHAR(MAX) = REPLACE(@P_ORDER_TYPE, '''', '`'),
    @@REQ_STATUS VARCHAR(MAX) = @P_STATUS;
	
	

SET @@QUERY = '
SELECT
    NOREG ,
    HOST_COMPANY ,
    HOST_COUNTRY ,
    PERIODE_FROM , 
    PERIODE_TO ,
    HOST_DIVISION ,
    HOST_DEPARTMENT ,
    HOST_SECTION ,
    RESPONSIBILITY ,
    ACCOMPLISHMENT ,
    REMARK_1 ,
    REMARK_2 ,
    CREATED_DT ,
    CREATED_BY 
    FROM PDI.TB_M_PROFILE_ICT_HISTORY
---
WHERE 
    1=1 
';

IF(@@REQ_STATUS != '')  BEGIN
    SET @@QUERY = @@QUERY + ' AND NOREG = '''+@@NOREG+''' ';
END;

EXECUTE (@@QUERY)