DECLARE 
    @@QUERY VARCHAR(MAX),
    @@NOREG VARCHAR(MAX) = @P_NOREG,
    @@REQ_STATUS VARCHAR(MAX) = @P_STATUS,
    @@BASE_URL VARCHAR(MAX) = @P_URL
;



SET @@QUERY = '
SELECT
    NOREG ,
    LANGUAGE_ID ,
    SKILL_LEVEL ,
    SCORE ,
    LANGUAGE_TEST ,
    CERTIFICATE_NAME ,
    CONCAT('''+@@BASE_URL+''', CERTIFICATE_PATH) AS CERTIFICATE_PATH ,
    VALID_TO ,
    REMARK_1 ,
    REMARK_2 ,
    CREATED_DT ,
    CREATED_BY
FROM PDI.TB_M_PROFILE_LANGUAGE
WHERE 
    1=1 
    AND NOREG = '''+@@NOREG+''' 
';

 
 
EXECUTE (@@QUERY);
