IF OBJECT_ID(N'tempdb..#T1') IS NOT NULL
BEGIN
	DROP TABLE #T1
END
IF OBJECT_ID(N'tempdb..#T2') IS NOT NULL
BEGIN
	DROP TABLE #T2
END
CREATE TABLE #T1
(
	LADLE_CD varchar(20)
	, LADLE_NM varchar(20)
	, PRODUCT_TYPE_1_CNT int
	, PRODUCT_TYPE_2_CNT int
	, PRODUCT_TYPE_3_CNT int
	, PRODUCT_TYPE_4_CNT int
);
CREATE TABLE #T2
(
	LADLE_CD varchar(20)
	, PRODUCT_TYPE varchar(20)
);

INSERT INTO #T1 (LADLE_CD, LADLE_NM, PRODUCT_TYPE_1_CNT, PRODUCT_TYPE_2_CNT, PRODUCT_TYPE_3_CNT, PRODUCT_TYPE_4_CNT)
SELECT 
 TB_M_SYSTEM.SYSTEM_CD, TB_M_SYSTEM.SYSTEM_VALUE AS LADLE_NM
, COUNT(CASE WHEN TB_R_POURING_FLASK.PRODUCT_TYPE = 1 THEN POURING_FLASK_ID END) AS PRODUCT_TYPE_1_CNT
, COUNT(CASE WHEN TB_R_POURING_FLASK.PRODUCT_TYPE = 2 THEN POURING_FLASK_ID END) AS PRODUCT_TYPE_2_CNT
, COUNT(CASE WHEN TB_R_POURING_FLASK.PRODUCT_TYPE = 3 THEN POURING_FLASK_ID END) AS PRODUCT_TYPE_3_CNT
, COUNT(CASE WHEN TB_R_POURING_FLASK.PRODUCT_TYPE = 4 THEN POURING_FLASK_ID END) AS PRODUCT_TYPE_4_CNT
FROM TB_M_SYSTEM
LEFT JOIN TB_R_POURING ON TB_R_POURING.LADLE_CD = TB_M_SYSTEM.SYSTEM_CD AND TB_R_POURING.MELTING_ID IN (SELECT MELTING_ID FROM TB_R_MELTING WHERE PRODUCTION_DT = @_PRODUCTION_DT AND SHIFT_CD = @_SHIFT_CD)
LEFT JOIN TB_R_POURING_FLASK ON TB_R_POURING_FLASK.POURING_ID = TB_R_POURING.POURING_ID AND FLASK_STS = '1'
WHERE SYSTEM_TYPE = 'LADLE_CD'
GROUP BY TB_M_SYSTEM.SYSTEM_CD, TB_M_SYSTEM.SYSTEM_VALUE, LADLE_CD
ORDER BY SYSTEM_VALUE;

INSERT INTO #T2 (LADLE_CD, PRODUCT_TYPE)
SELECT LADLE_CD, PRODUCT_TYPE FROM
(
SELECT 
	ROW_NUMBER() OVER (
	PARTITION BY TB_R_POURING.LADLE_CD
	ORDER BY TB_R_POURING.POURING_ID
	) AS RN
	, POURING_ID
	, TB_R_POURING.MELTING_ID
	, LADLE_CD
	, TB_R_MELTING.PRODUCT_TYPE
	FROM TB_R_POURING
	LEFT JOIN TB_R_MELTING ON TB_R_POURING.MELTING_ID = TB_R_MELTING.MELTING_ID 
	WHERE TB_R_MELTING.MELTING_ID  IN (SELECT MELTING_ID FROM TB_R_MELTING WHERE PRODUCTION_DT = @_PRODUCTION_DT AND SHIFT_CD = @_SHIFT_CD)
)TMP
WHERE RN = 1;

SELECT 
#T1.LADLE_CD, LADLE_NM
, CASE WHEN PRODUCT_TYPE = 'TR' THEN 'FC' WHEN PRODUCT_TYPE = 'Camshaft' OR PRODUCT_TYPE = 'Crank' THEN	 'FCD' END AS PRODUCT_TYPE
, CASE WHEN PRODUCT_TYPE IS NOT NULL THEN PRODUCT_TYPE_1_CNT END AS PRODUCT_TYPE_1_CNT
, CASE WHEN PRODUCT_TYPE IS NOT NULL THEN PRODUCT_TYPE_2_CNT END AS PRODUCT_TYPE_2_CNT
, CASE WHEN PRODUCT_TYPE IS NOT NULL THEN PRODUCT_TYPE_3_CNT END AS PRODUCT_TYPE_3_CNT
, CASE WHEN PRODUCT_TYPE IS NOT NULL THEN PRODUCT_TYPE_4_CNT END AS PRODUCT_TYPE_4_CNT
, CAST(
	(#T1.PRODUCT_TYPE_1_CNT/(SELECT CAST(SYSTEM_VALUE AS decimal(18,2)) FROM TB_M_SYSTEM WHERE SYSTEM_TYPE = 'REPORT_POURING' AND SYSTEM_CD = '1TR_WEIGHT')) 
	+ (#T1.PRODUCT_TYPE_2_CNT/(SELECT CAST(SYSTEM_VALUE AS decimal(18,2)) FROM TB_M_SYSTEM WHERE SYSTEM_TYPE = 'REPORT_POURING' AND SYSTEM_CD = '2TR_WEIGHT')) 
	+ (#T1.PRODUCT_TYPE_3_CNT/(SELECT CAST(SYSTEM_VALUE AS decimal(18,2)) FROM TB_M_SYSTEM WHERE SYSTEM_TYPE = 'REPORT_POURING' AND SYSTEM_CD = 'CAMS_WEIGHT')) 
	+ (#T1.PRODUCT_TYPE_4_CNT/(SELECT CAST(SYSTEM_VALUE AS decimal(18,2)) FROM TB_M_SYSTEM WHERE SYSTEM_TYPE = 'REPORT_POURING' AND SYSTEM_CD = 'CRANK_WEIGHT')) 
	AS decimal(18,2)
) AS TONAGE
FROM #T1
LEFT JOIN #T2 ON #T2.LADLE_CD = #T1.LADLE_CD
ORDER BY #T1.LADLE_NM


IF OBJECT_ID(N'tempdb..#T1') IS NOT NULL
BEGIN
	DROP TABLE #T1
END
IF OBJECT_ID(N'tempdb..#T2') IS NOT NULL
BEGIN
	DROP TABLE #T2
END