SELECT TOP 1 POURING_SHIFT_ID, COMPANY_ID, PLANT_CD, PRODUCTION_DT, SHIFT_CD, SHIFT_TYPE, CYCLE_TIME, OPR_CD, GH_LH, A2, B2, C2, D2, E2, F2, G2, H2, I2
, J2, LOT_DAY_SHIFT_CAM, LOT_DAY_SHIFT_CRANK, START_BURNER_WEST, FINISH_BURNER_WEST, START_BURNER_EAST, FINISH_BURNER_EAST, NOTES
 FROM
 TB_R_POURING_SHIFT_SUM
 WHERE POURING_SHIFT_ID = @_POURING_SHIFT_ID;