SELECT TB_R_QC_SHIFT_DEFECT.DEFECT_TYPE, TB_R_QC_SHIFT_DEFECT.PRODUCT_TYPE, TB_R_QC_SHIFT_DEFECT.DEFECT_ID, TB_M_SYSTEM.SYSTEM_VALUE, TB_R_QC_SHIFT_DEFECT.TOTAL_PCS
FROM TB_R_QC_GATE 
JOIN TB_R_QC_SHIFT_SUM ON TB_R_QC_SHIFT_SUM.PRODUCTION_DT = TB_R_QC_GATE.PRODUCTION_DT AND TB_R_QC_SHIFT_SUM.SHIFT_CD = TB_R_QC_GATE.SHIFT_CD AND TB_R_QC_SHIFT_SUM.SHIFT_TYPE = TB_R_QC_GATE.SHIFT_TYPE
JOIN TB_R_QC_SHIFT_DEFECT ON TB_R_QC_SHIFT_DEFECT.QC_SHIFT_ID = TB_R_QC_SHIFT_SUM.QC_SHIFT_ID
JOIN TB_M_SYSTEM ON TB_M_SYSTEM.SYSTEM_TYPE = 'DEFECT_FINISHING' AND TB_M_SYSTEM.SYSTEM_CD = TB_R_QC_SHIFT_DEFECT.DEFECT_ID 
WHERE TB_R_QC_GATE.PRODUCTION_DT = @_PRODUCTION_DT AND TB_R_QC_GATE.SHIFT_CD = @_SHIFT_CD
GROUP BY TB_R_QC_SHIFT_DEFECT.DEFECT_ID, TB_M_SYSTEM.SYSTEM_VALUE, TB_R_QC_SHIFT_DEFECT.PRODUCT_TYPE, TB_R_QC_SHIFT_DEFECT.TOTAL_PCS, TB_R_QC_SHIFT_DEFECT.DEFECT_TYPE
ORDER BY TB_R_QC_SHIFT_DEFECT.DEFECT_TYPE, TB_R_QC_SHIFT_DEFECT.PRODUCT_TYPE;