SELECT TB_R_POURING_SHIFT_TEMP.POURING_TEMP_ID, TB_R_POURING_SHIFT_TEMP.POURING_SHIFT_ID, TB_R_POURING_SHIFT_TEMP.TEMP_NO, TB_R_POURING_SHIFT_TEMP.TEMP_ACTUAL, TB_R_POURING_SHIFT_TEMP.TEMP_STANDARD, TB_R_POURING_SHIFT_TEMP.TEMP_TYPE 
FROM TB_R_POURING_SHIFT_TEMP
 WHERE TEMP_TYPE = @_TEMP_TYPE AND  POURING_SHIFT_ID = @_POURING_SHIFT_ID