IF OBJECT_ID(N'tempdb..#T1') IS NOT NULL
BEGIN
	DROP TABLE #T1
END
IF OBJECT_ID(N'tempdb..#T2') IS NOT NULL
BEGIN
	DROP TABLE #T2
END
CREATE TABLE #T1
(
	LADLE_CD varchar(20)
	, LADLE_NM varchar(20)
	, LADLE_CNT int
);
CREATE TABLE #T2
(
	LADLE_CD varchar(20)
	, PRODUCT_TYPE varchar(20)
);
INSERT INTO #T1 (LADLE_CD, LADLE_NM, LADLE_CNT)
SELECT SYSTEM_CD AS LADLE_CD, SYSTEM_VALUE AS LADLE_NM, COUNT(POURING_ID) AS LADLE_CNT
FROM TB_M_SYSTEM 
LEFT JOIN TB_R_POURING ON TB_R_POURING.LADLE_CD = SYSTEM_CD AND TB_R_POURING.MELTING_ID IN (SELECT MELTING_ID FROM TB_R_MELTING WHERE PRODUCTION_DT = @_PRODUCTION_DT AND SHIFT_CD = @_SHIFT_CD)
WHERE TB_M_SYSTEM.SYSTEM_TYPE = 'LADLE_CD' 
GROUP BY SYSTEM_CD, SYSTEM_VALUE
ORDER BY SYSTEM_VALUE;

INSERT INTO #T2 (LADLE_CD, PRODUCT_TYPE)
SELECT LADLE_CD, PRODUCT_TYPE FROM
(
SELECT 
	ROW_NUMBER() OVER (
	PARTITION BY TB_R_POURING.LADLE_CD
	ORDER BY TB_R_POURING.POURING_ID
	) AS RN
	, POURING_ID
	, TB_R_POURING.MELTING_ID
	, LADLE_CD
	, TB_R_MELTING.PRODUCT_TYPE
	FROM TB_R_POURING
	LEFT JOIN TB_R_MELTING ON TB_R_POURING.MELTING_ID = TB_R_MELTING.MELTING_ID 
	WHERE TB_R_MELTING.PRODUCTION_DT = @_PRODUCTION_DT AND TB_R_MELTING.SHIFT_CD = @_SHIFT_CD
)TMP
WHERE RN = 1;

SELECT 
#T1.LADLE_CD, LADLE_NM
, CASE WHEN PRODUCT_TYPE = 'TR' THEN 'FC' WHEN PRODUCT_TYPE = 'Camshaft' OR PRODUCT_TYPE = 'Crank' THEN	 'FCD' END AS PRODUCT_TYPE
, CASE WHEN LADLE_CNT > 0 THEN LADLE_CNT END AS LADLE_CNT
FROM #T1
LEFT JOIN #T2 ON #T2.LADLE_CD = #T1.LADLE_CD
ORDER BY #T1.LADLE_NM


IF OBJECT_ID(N'tempdb..#T1') IS NOT NULL
BEGIN
	DROP TABLE #T1
END
IF OBJECT_ID(N'tempdb..#T2') IS NOT NULL
BEGIN
	DROP TABLE #T2
END