SELECT 
	TB_M_MATERIAL.MATERIAL_NAME
	, TB_R_MELTING_SHIFT_ADJ_STD.PREP
	, TB_R_MELTING_SHIFT_ADJ_STD.LOW_VAL																	
	, TB_R_MELTING_SHIFT_ADJ_STD.HIGH_VAL												
FROM TB_M_MATERIAL 
LEFT JOIN TB_R_MELTING_SHIFT_ADJ_STD ON TB_R_MELTING_SHIFT_ADJ_STD.ADJUST_CD = TB_M_MATERIAL.MATERIAL_CD AND TB_R_MELTING_SHIFT_ADJ_STD.MELTING_SUM_ID = @_MELTING_SUM_ID
	WHERE MATERIAL_TYPE = 'MELTING' 