
IF OBJECT_ID(N'tempdb..#T1') IS NOT NULL
BEGIN
	DROP TABLE #T1
END
CREATE TABLE #T1
(
RN INT, PRODUCTION_DT DATE, POURING_ID INT, FINAL_JUDGEMENT varchar(20), TAPPING_NO INT, START_POURING varchar(10)
, FURNACE_CD varchar(20),CHARGE_NO INT, LADLE_CD varchar(20), LADLE_NM varchar(255), TEMPERATURE DECIMAL(18,2), TOTAL_POURING_TIME DECIMAL(18,2)
, MOLTEN_METAL varchar(255), CHILL_TEST DECIMAL(18, 2), LOT_NO INT, NAME varchar(50), FLASK_STS char(1)
, PRODUCT_TYPE varchar(20), PRODUCT_TYPE_NM varchar(255), FLASK_NO INT, SHIFT_CD varchar(20), SHIFT_CD_NM varchar(20), SHIFT_TYPE varchar(20), SHIFT_TYPE_NM varchar(20)
, OPR_NM varchar(50)
);
IF OBJECT_ID(N'tempdb..#T2') IS NOT NULL
BEGIN
	DROP TABLE #T2
END
CREATE TABLE #T2
(
	PRODUCTION_DT DATE
	, SHIFT_CD varchar(20)
);

declare @@where varchar(max);
SET @@where = '1=1 AND TB_R_MELTING.TAPPING_STS = ''2''' ;
IF @_PRODUCTION_MT != ''
BEGIN
	SET @@where += ' AND LEFT(TB_R_MELTING.PRODUCTION_DT, 7) = ''' + @_PRODUCTION_MT + ''''
END
IF @_SHIFT_CD != ''
BEGIN
	SET @@where += ' AND LEFT(TB_R_MELTING.SHIFT_CD, 7) = ''' + @_SHIFT_CD + ''''
END
IF @_START_DT != '' AND @_END_DT != ''
BEGIN
	--SET @@where += ' AND TB_R_MELTING.PRODUCTION_DT BETWEEN '''+@_START_DT+''' AND '''+@_START_DT+''''
	SET @@where += ' AND TB_R_MELTING.PRODUCTION_DT = '''+@_START_DT+''' '
END
		

DECLARE @@SQL as varchar(max);

SET @@SQL = '
	SELECT 
		 TB_R_MELTING.MELTING_ID
		 , TB_R_MELTING.PRODUCTION_DT
		 , TB_R_MELTING.SHIFT_CD
		 , TB_R_MELTING.TAPPING_NO																	
		 , TB_R_MELTING.FURNACE_CD																	
		 , TB_R_MELTING.CHARGE_NO																	
		 -- -- , SYSTEM_VALUE AS MOLTEN_MATERIAL																	
		 , TB_R_MELTING.TOTAL_INGOT AS INGOT																	
		 , TB_R_MELTING.TOTAL_SCRAP_NON_GALVANIS AS SCRAP_NON_GALVANIS																	
		 , TB_R_MELTING.TOTAL_SCRAP_GALVANIS AS SCRAP_GALVANIS
		 , TB_R_MELTING.TOTAL_RETURN AS [RETURN]	
		 , TB_R_MELTING.TOTAL_SN AS SN																	
		 , TB_R_MELTING.TOTAL_CARBON AS CARBON																	
		 , TB_R_MELTING.TOTAL_SILICON AS SILICON																	
		 , TB_R_MELTING.TOTAL_MANGAN AS MANGAN
		 , TB_R_CAMS.CAM_ID
		 , TB_R_CAMS.FINAL_STS
		 , CASE WHEN TB_R_CAMS.FINAL_STS = 1 THEN TB_R_CAMS.MATERIAL_C END AS MATERIAL_C
		 , CASE WHEN TB_R_CAMS.FINAL_STS = 1 THEN TB_R_CAMS.MATERIAL_SI END AS MATERIAL_SI
		 , CASE WHEN TB_R_CAMS.FINAL_STS = 1 THEN TB_R_CAMS.MATERIAL_MN END AS MATERIAL_MN
		 , CASE WHEN TB_R_CAMS.FINAL_STS = 1 THEN TB_R_CAMS.MATERIAL_P END AS MATERIAL_P
		 , CASE WHEN TB_R_CAMS.FINAL_STS = 1 THEN TB_R_CAMS.MATERIAL_S END AS MATERIAL_S
		 , CASE WHEN TB_R_CAMS.FINAL_STS = 1 THEN TB_R_CAMS.MATERIAL_CR END AS MATERIAL_CR
		 , CASE WHEN TB_R_CAMS.FINAL_STS = 1 THEN TB_R_CAMS.MATERIAL_MG END AS MATERIAL_MG
		 , CASE WHEN TB_R_CAMS.FINAL_STS = 1 THEN TB_R_CAMS.MATERIAL_SB END AS MATERIAL_SB
		 , CASE WHEN TB_R_CAMS.FINAL_STS = 1 THEN TB_R_CAMS.MATERIAL_ZN END AS MATERIAL_ZN
		 , CASE WHEN TB_R_CAMS.FINAL_STS = 1 THEN TB_R_CAMS.MATERIAL_CE END AS MATERIAL_CE
		 , CASE WHEN TB_R_CAMS.FINAL_STS = 1 THEN TB_R_CAMS.MATERIAL_MO END AS MATERIAL_MO
		 , CASE WHEN TB_R_CAMS.FINAL_STS = 1 THEN TB_R_CAMS.MATERIAL_NI END AS MATERIAL_NI
		 , CASE WHEN TB_R_CAMS.FINAL_STS = 1 THEN TB_R_CAMS.MATERIAL_SN END AS MATERIAL_SN
		 , CASE WHEN TB_R_CAMS.FINAL_STS = 1 THEN TB_R_CAMS.MATERIAL_CU END AS MATERIAL_CU
		 , TB_R_MELTING.INNOCULAN_INNOCARB																	
		 , TB_R_MELTING.INNOCULAN_LMC
		 , TB_R_MELTING.SB
		 , TB_R_MELTING.INNOCULAN_LG
		 , TB_R_MELTING.FE_SI_MG
		 , TB_R_MELTING.CU
		 , TB_R_MELTING.TAPPING_TIME
		 , TB_R_MELTING.TAPPING_WEIGHT
		 , TB_R_MELTING.TAPPING_TEMPERATURE
		 , COALESCE(stuff((
				select '','' + tt.PRODUCT_TYPE
				from TB_R_POURING t
				LEFT JOIN TB_R_POURING_FLASK tt ON t.POURING_ID = tt.POURING_ID
				where t.MELTING_ID = TB_R_MELTING.MELTING_ID AND tt.PRODUCT_TYPE IS NOT NULL AND tt.LOT_NO IS NOT NULL AND tt.PRODUCT_TYPE != ''''
				GROUP BY tt.PRODUCT_TYPE, tt.LOT_NO
				ORDER BY tt.PRODUCT_TYPE
				for xml path('''')
			),1,1,''''), '''') AS PRODUCT_TYPE
		, COALESCE(stuff((
				select '','' + CAST(COUNT(1) AS VARCHAR)
				from TB_R_POURING t
				JOIN TB_R_POURING_FLASK tt ON t.POURING_ID = tt.POURING_ID
				where t.MELTING_ID = TB_R_MELTING.MELTING_ID AND tt.PRODUCT_TYPE IS NOT NULL AND tt.LOT_NO IS NOT NULL AND tt.PRODUCT_TYPE != ''''
				GROUP BY tt.PRODUCT_TYPE, tt.LOT_NO
				ORDER BY tt.PRODUCT_TYPE
				for xml path('''')
			),1,1,''''), '''')
			as PRODUCT_TYPE_FLASK
		, COALESCE(stuff((
				select '','' + CAST(COUNT(1) AS VARCHAR)
				from TB_R_POURING t
				JOIN TB_R_POURING_FLASK tt ON t.POURING_ID = tt.POURING_ID
				where t.MELTING_ID = TB_R_MELTING.MELTING_ID AND tt.PRODUCT_TYPE IS NOT NULL AND tt.LOT_NO IS NOT NULL AND tt.PRODUCT_TYPE != '''' AND tt.PRODUCT_TYPE = 1
				GROUP BY tt.PRODUCT_TYPE, tt.LOT_NO
				ORDER BY tt.PRODUCT_TYPE
				for xml path('''')
			),1,1,''''), '''')
			as PRODUCT_TYPE_1_FLASK
		, COALESCE(stuff((
				select '','' + CAST(COUNT(1) AS VARCHAR)
				from TB_R_POURING t
				JOIN TB_R_POURING_FLASK tt ON t.POURING_ID = tt.POURING_ID
				where t.MELTING_ID = TB_R_MELTING.MELTING_ID AND tt.PRODUCT_TYPE IS NOT NULL AND tt.LOT_NO IS NOT NULL AND tt.PRODUCT_TYPE != '''' AND tt.PRODUCT_TYPE = 2
				GROUP BY tt.PRODUCT_TYPE, tt.LOT_NO
				ORDER BY tt.PRODUCT_TYPE
				for xml path('''')
			),1,1,''''), '''')
			as PRODUCT_TYPE_2_FLASK	
		, COALESCE(stuff((
				select '','' + CAST(COUNT(1) AS VARCHAR)
				from TB_R_POURING t
				JOIN TB_R_POURING_FLASK tt ON t.POURING_ID = tt.POURING_ID
				where t.MELTING_ID = TB_R_MELTING.MELTING_ID AND tt.PRODUCT_TYPE IS NOT NULL AND tt.LOT_NO IS NOT NULL AND tt.PRODUCT_TYPE != '''' AND tt.PRODUCT_TYPE = 3
				GROUP BY tt.PRODUCT_TYPE, tt.LOT_NO
				ORDER BY tt.PRODUCT_TYPE
				for xml path('''')
			),1,1,''''), '''')
			as PRODUCT_TYPE_3_FLASK	
		, COALESCE(stuff((
				select '','' + CAST(COUNT(1) AS VARCHAR)
				from TB_R_POURING t
				JOIN TB_R_POURING_FLASK tt ON t.POURING_ID = tt.POURING_ID
				where t.MELTING_ID = TB_R_MELTING.MELTING_ID AND tt.PRODUCT_TYPE IS NOT NULL AND tt.LOT_NO IS NOT NULL AND tt.PRODUCT_TYPE != '''' AND tt.PRODUCT_TYPE = 4
				GROUP BY tt.PRODUCT_TYPE, tt.LOT_NO
				ORDER BY tt.PRODUCT_TYPE
				for xml path('''')
			),1,1,''''), '''')
			as PRODUCT_TYPE_4_FLASK																
			, RIGHT(TB_R_MELTING.PRODUCTION_DT, 2) AS SHEET_NM

			
			, COALESCE((SELECT SYSTEM_VALUE FROM TB_M_SYSTEM WHERE SYSTEM_TYPE = ''REPORT_POURING'' AND SYSTEM_CD = ''PIC_RED''), '''') AS PIC_RED
			, COALESCE((SELECT SYSTEM_VALUE FROM TB_M_SYSTEM WHERE SYSTEM_TYPE = ''REPORT_POURING'' AND SYSTEM_CD = ''PIC_WHITE''), '''') AS PIC_WHITE
			, COALESCE((SELECT SYSTEM_VALUE FROM TB_M_SYSTEM WHERE SYSTEM_TYPE = ''REPORT_POURING'' AND SYSTEM_CD = ''SH_NAME''), '''') AS SECTION_HEAD
			, COALESCE((SELECT SYSTEM_VALUE FROM TB_M_SYSTEM WHERE SYSTEM_TYPE = ''REPORT_POURING'' AND SYSTEM_CD = ''LH_NAME''), '''') AS LINE_HEAD
			, COALESCE((SELECT SYSTEM_VALUE FROM TB_M_SYSTEM WHERE SYSTEM_TYPE = ''REPORT_POURING'' AND SYSTEM_CD = ''GH_NAME''), '''') AS GROUP_HEAD

			, SSS.SYSTEM_VALUE AS SHIFT_CD_NM
			, SSSS.SYSTEM_VALUE AS SHIFT_TYPE_NM
			, CASE WHEN TB_R_MELTING.PRODUCT_TYPE = ''TR'' THEN ''FC'' WHEN TB_R_MELTING.PRODUCT_TYPE = ''Crank'' OR TB_R_MELTING.PRODUCT_TYPE = ''Camshaft'' THEN ''FCD'' END AS MOLTEN_METAL
			, TB_R_MELTING_SHIFT_SUM.MELTING_SUM_ID
		 FROM TB_R_MELTING
		 LEFT JOIN TB_R_CAMS ON TB_R_CAMS.MELTING_ID = TB_R_MELTING.MELTING_ID AND TB_R_CAMS.FINAL_STS=1
		 LEFT JOIN TB_M_SYSTEM SSS ON TB_R_MELTING.SHIFT_CD = SSS.SYSTEM_CD AND SSS.SYSTEM_TYPE = ''SHIFT_CD''
		 LEFT JOIN TB_M_SYSTEM SSSS ON TB_R_MELTING.SHIFT_TYPE = SSSS.SYSTEM_CD AND SSSS.SYSTEM_TYPE = ''SHIFT_TYPE''
		 LEFT JOIN TB_R_MELTING_SHIFT_SUM ON TB_R_MELTING_SHIFT_SUM.PRODUCTION_DT = TB_R_MELTING.PRODUCTION_DT AND TB_R_MELTING_SHIFT_SUM.SHIFT_CD = TB_R_MELTING.SHIFT_CD 
		 --AND TB_R_MELTING_SHIFT_SUM.SHIFT_TYPE = TB_R_MELTING.SHIFT_TYPE
				WHERE 
				' + @@where + '
		 ORDER BY TB_R_MELTING.TAPPING_NO ASC, TB_R_MELTING.PRODUCTION_DT, TB_R_MELTING.SHIFT_CD;	
		';
	IF @_TYPE = 'HEADER'
	BEGIN
		SELECT DISTINCT LEFT(TB_R_MELTING.PRODUCTION_DT, 7) AS PRODUCTION_MT, TB_R_MELTING.SHIFT_CD
		, (SELECT REPLACE(REPLACE(REPLACE(SYSTEM_REMARK, '{shift}', CASE TB_R_MELTING.SHIFT_CD WHEN 'R' THEN 'Red' WHEN 'W' THEN 'White' END ), '{month}'
		, CASE MONTH(PRODUCTION_DT) 
			WHEN 1 THEN 'Januari' 
			WHEN 2 THEN 'Februari' 
			WHEN 3 THEN 'Maret' 
			WHEN 4 THEN 'April' 
			WHEN 5 THEN 'Mei' 
			WHEN 6 THEN 'Juni' 
			WHEN 7 THEN 'Juli' 
			WHEN 8 THEN 'Agustus' 
			WHEN 9 THEN 'September' 
			WHEN 10 THEN 'Oktober' 
			WHEN 11 THEN 'November' 
			WHEN 12 THEN 'Desember' 
			ELSE '' END 
		)
		, '{year}', YEAR(PRODUCTION_DT)) FROM TB_M_SYSTEM WHERE SYSTEM_TYPE = 'REPORT_LIST' AND SYSTEM_CD = 'MELT_ASPNETMVC3TDKRO3') AS REPORT_NAME
		, CASE TB_R_MELTING.SHIFT_CD WHEN 'R' THEN 'Red' WHEN 'W' THEN 'White' END  AS SHIFT_CD_NM
		, DATEDIFF(MINUTE, MIN(TAPPING_TIME), MAX(TAPPING_TIME)) AS PRODUCTION_TM
		FROM TB_R_MELTING
		WHERE 
		--TB_R_MELTING.PRODUCTION_DT BETWEEN @_START_DT AND @_END_DT 
		TB_R_MELTING.PRODUCTION_DT = @_START_DT 
		AND TB_R_MELTING.TAPPING_STS = '2'
		GROUP BY TB_R_MELTING.PRODUCTION_DT, TB_R_MELTING.SHIFT_CD
		ORDER BY PRODUCTION_MT, TB_R_MELTING.SHIFT_CD;
	END
	ELSE
	BEGIN
		EXEC (@@SQL);
	END


IF OBJECT_ID(N'tempdb..#T1') IS NOT NULL
BEGIN
	DROP TABLE #T1
END
IF OBJECT_ID(N'tempdb..#T2') IS NOT NULL
BEGIN
	DROP TABLE #T2
END
