SELECT 
	TB_M_MATERIAL.MATERIAL_ID, TB_M_MATERIAL.MATERIAL_NAME 
	, COALESCE(TB_R_QC_SHIFT_MATERIAL.START_STOCK, 0) AS START_STOCK
	, COALESCE(TB_R_QC_SHIFT_MATERIAL.BON, 0) AS BON
	, COALESCE(TB_R_QC_SHIFT_MATERIAL.STOCK_USED, 0) AS STOCK_USED
FROM TB_M_MATERIAL 
LEFT JOIN TB_R_QC_SHIFT_MATERIAL ON 
	TB_R_QC_SHIFT_MATERIAL.MATERIAL_ID = TB_M_MATERIAL.MATERIAL_ID AND TB_R_QC_SHIFT_MATERIAL.QC_SHIFT_ID = @_QC_SHIFT_ID
WHERE TB_M_MATERIAL.MATERIAL_TYPE = 'FINISHING_USED';