SELECT 
	TB_M_USER.NAME
	, TB_R_MELTING_SHIFT_MP.JOB_CD
	, S.SYSTEM_VALUE AS JOB_NM
	, SS.SYSTEM_VALUE AS ABSENT_NM
	, TB_R_MELTING_SHIFT_MP.A1
	, TB_R_MELTING_SHIFT_MP.B1
	, TB_R_MELTING_SHIFT_MP.C1
	, TB_R_MELTING_SHIFT_MP.D1
	, TB_R_MELTING_SHIFT_MP.E1
	, TB_R_MELTING_SHIFT_MP.F1
	, TB_R_MELTING_SHIFT_MP.G1
	, TB_R_MELTING_SHIFT_MP.H1
	, TB_R_MELTING_SHIFT_MP.I1
	, TB_R_MELTING_SHIFT_MP.J1
	, TB_R_MELTING_SHIFT_MP.A2
	, TB_R_MELTING_SHIFT_MP.B2
	, TB_R_MELTING_SHIFT_MP.C2
	, TB_R_MELTING_SHIFT_MP.D2
	, TB_R_MELTING_SHIFT_MP.E2
	, TB_R_MELTING_SHIFT_MP.F2
	, TB_R_MELTING_SHIFT_MP.G2
	, TB_R_MELTING_SHIFT_MP.H2
	, TB_R_MELTING_SHIFT_MP.I2
	, TB_R_MELTING_SHIFT_MP.J2
	, (SELECT SYSTEM_VALUE FROM TB_M_SYSTEM WHERE SYSTEM_TYPE = 'JOB_TYPE' AND SYSTEM_CD = 1) AS JOB_TYPE_1
	, (SELECT SYSTEM_VALUE FROM TB_M_SYSTEM WHERE SYSTEM_TYPE = 'JOB_TYPE' AND SYSTEM_CD = 2) AS JOB_TYPE_2
	, (SELECT SYSTEM_VALUE FROM TB_M_SYSTEM WHERE SYSTEM_TYPE = 'JOB_TYPE' AND SYSTEM_CD = 3) AS JOB_TYPE_3
	, (SELECT SYSTEM_VALUE FROM TB_M_SYSTEM WHERE SYSTEM_TYPE = 'JOB_TYPE' AND SYSTEM_CD = 4) AS JOB_TYPE_4
FROM TB_R_MELTING_SHIFT_MP
LEFT JOIN TB_M_USER ON TB_M_USER.USER_ID = TB_R_MELTING_SHIFT_MP.MP_CD
LEFT JOIN TB_M_SYSTEM S ON S.SYSTEM_TYPE = 'JOB_TYPE' AND S.SYSTEM_CD = TB_R_MELTING_SHIFT_MP.JOB_CD
LEFT JOIN TB_M_SYSTEM SS ON SS.SYSTEM_TYPE = 'ABSENT_TYPE' AND SS.SYSTEM_CD = TB_R_MELTING_SHIFT_MP.ABSENT_CD
WHERE TB_R_MELTING_SHIFT_MP.MELTING_SUM_ID = @_MELTING_SUM_ID;