SELECT 
TB_M_MATERIAL.MATERIAL_NAME
, TB_R_GENTAN.STANDARD_VAL
, TB_R_GENTAN.ACTUAL_VAL
FROM TB_M_MATERIAL 
LEFT JOIN TB_R_GENTAN ON 
	TB_R_GENTAN.MATERIAL_ID = TB_M_MATERIAL.MATERIAL_ID 
	AND TB_R_GENTAN.PRODUCTION_DATE = @_PRODUCTION_DT
	AND TB_R_GENTAN.SHIFT_CD = @_SHIFT_CD
WHERE MATERIAL_TYPE = 'GENTAN'