SELECT 
	TB_M_MATERIAL.MATERIAL_ID, TB_M_MATERIAL.MATERIAL_NAME, TB_M_MATERIAL.UOM_ID
	, TB_M_SYSTEM.SYSTEM_VALUE AS UOM_NM
	, COALESCE(TB_R_QC_SHIFT_SAND.UNIT_TOTAL, 0) AS UNIT_TOTAL
FROM TB_M_MATERIAL 
LEFT JOIN TB_R_QC_SHIFT_SAND ON 
	TB_R_QC_SHIFT_SAND.UNIT_ID = TB_M_MATERIAL.MATERIAL_ID AND TB_R_QC_SHIFT_SAND.QC_SHIFT_ID = @_QC_SHIFT_ID
JOIN TB_M_SYSTEM ON TB_M_SYSTEM.SYSTEM_TYPE = 'UOM' AND TB_M_SYSTEM.SYSTEM_CD = TB_M_MATERIAL.UOM_ID
WHERE TB_M_MATERIAL.MATERIAL_TYPE = 'FINISHING_WASTE';