SELECT TB_R_POURING_SHIFT_MATERIAL.POURING_MATERIAL_ID
, TB_M_MATERIAL.MATERIAL_NAME
, TB_R_POURING_SHIFT_MATERIAL.USED
, TB_M_SYSTEM.SYSTEM_VALUE AS UOM_NM
 FROM TB_M_MATERIAL
 LEFT JOIN TB_R_POURING_SHIFT_MATERIAL ON TB_R_POURING_SHIFT_MATERIAL.MATERIAL_ID = TB_M_MATERIAL.MATERIAL_ID
 LEFT JOIN TB_M_SYSTEM ON TB_R_POURING_SHIFT_MATERIAL.UNIT_CD = TB_M_SYSTEM.SYSTEM_CD AND TB_M_SYSTEM.SYSTEM_TYPE = 'UOM'
 WHERE TB_M_MATERIAL.MATERIAL_TYPE = 'POURING' AND POURING_SHIFT_ID = @_POURING_SHIFT_ID
 ORDER BY TB_M_MATERIAL.MATERIAL_ID
 ;