
IF OBJECT_ID(N'tempdb..#T1') IS NOT NULL
BEGIN
	DROP TABLE #T1
END
CREATE TABLE #T1
(
RN INT, PRODUCTION_DT DATE, POURING_ID INT, FINAL_JUDGEMENT varchar(20), TAPPING_NO INT, START_POURING varchar(10)
, FURNACE_CD varchar(20), LADLE_CD varchar(20), LADLE_NM varchar(255), TEMPERATURE DECIMAL(18,2), TOTAL_POURING_TIME DECIMAL(18,2)
, MOLTEN_METAL varchar(255), CHILL_TEST DECIMAL(18, 2), LOT_NO INT, NAME varchar(50), FLASK_STS char(1)
, PRODUCT_TYPE varchar(20), PRODUCT_TYPE_NM varchar(255), FLASK_NO INT, SHIFT_CD varchar(20), SHIFT_CD_NM varchar(20), SHIFT_TYPE varchar(20), SHIFT_TYPE_NM varchar(20)
, OPR_NM varchar(50)
);
IF OBJECT_ID(N'tempdb..#T2') IS NOT NULL
BEGIN
	DROP TABLE #T2
END
CREATE TABLE #T2
(
	PRODUCTION_DT DATE
	, SHIFT_CD varchar(20)
	, SHIFT_CD_NM varchar(20)
);
DECLARE @@SQL as varchar(max);

declare @@where varchar(max);
SET @@where = '1=1' ;
IF @_PRODUCTION_MT != ''
BEGIN
	SET @@where += ' AND LEFT(TB_R_MELTING.PRODUCTION_DT, 7) = ''' + @_PRODUCTION_MT + ''''
END
IF @_SHIFT_CD != ''
BEGIN
	SET @@where += ' AND LEFT(TB_R_MELTING.SHIFT_CD, 7) = ''' + @_SHIFT_CD + ''''
END
IF @_START_DT != '' AND @_END_DT != ''
BEGIN
	SET @@where += ' AND TB_R_MELTING.PRODUCTION_DT BETWEEN '''+@_START_DT+''' AND '''+@_END_DT+''''
END
		

SET @@SQL = '
SELECT 
RN, PRODUCTION_DT, POURING_ID, FINAL_JUDGEMENT, TAPPING_NO, START_POURING, FURNACE_CD, LADLE_CD, LADLE_NM, TEMPERATURE, TOTAL_POURING_TIME, MOLTEN_METAL, CHILL_TEST, LOT_NO, NAME, FLASK_STS, 
PRODUCT_TYPE, PRODUCT_TYPE_NM, CASE WHEN RN <= 5 THEN 1 WHEN RN <= 10 THEN 2 WHEN RN <= 15 THEN 3 END AS FLASK_NO, SHIFT_CD, SHIFT_CD_NM, SHIFT_TYPE, SHIFT_TYPE_NM
	FROM(
		SELECT 
		   ROW_NUMBER() OVER (
			PARTITION BY TB_R_POURING.POURING_ID
			ORDER BY TB_R_POURING.POURING_ID
		   ) AS RN
		, TB_R_MELTING.PRODUCTION_DT
		, TB_R_POURING.POURING_ID
		, TB_R_POURING.FINAL_JUDGEMENT
		, TB_R_MELTING.TAPPING_NO
		, COALESCE(CAST(CAST(TB_R_POURING.START_POURING AS TIME) AS VARCHAR(5)), '''') AS START_POURING
		, TB_R_MELTING.FURNACE_CD
		, TB_R_POURING.LADLE_CD
		, S.SYSTEM_VALUE AS LADLE_NM
		, TB_R_POURING.TEMPERATURE
		, TB_R_POURING.TOTAL_POURING_TIME
		, CASE WHEN TB_R_MELTING.PRODUCT_TYPE = ''TR'' THEN ''FC'' WHEN TB_R_MELTING.PRODUCT_TYPE = ''Crank'' OR TB_R_MELTING.PRODUCT_TYPE = ''Camshaft'' THEN ''FCD'' END AS MOLTEN_METAL
		, TB_R_POURING.CHILL_TEST
		, TB_R_POURING_FLASK.LOT_NO
		, TB_M_USER.NAME
		, TB_R_POURING_FLASK.POURING_FLASK_ID
		, TB_R_POURING_FLASK.FLASK_STS
		, TB_R_MOULDING.PRODUCT_TYPE
		, SS.SYSTEM_VALUE AS PRODUCT_TYPE_NM
		, TB_R_MELTING.SHIFT_CD
		, SSS.SYSTEM_VALUE AS SHIFT_CD_NM
		, TB_R_MELTING.SHIFT_TYPE
		, SSSS.SYSTEM_VALUE AS SHIFT_TYPE_NM
		FROM TB_R_POURING
		JOIN TB_R_MELTING ON TB_R_POURING.MELTING_ID = TB_R_MELTING.MELTING_ID
		LEFT JOIN TB_R_POURING_FLASK ON TB_R_POURING_FLASK.POURING_ID = TB_R_POURING.POURING_ID
		LEFT JOIN TB_M_USER ON TB_M_USER.USER_ID = TB_R_POURING.MP_CD
		LEFT JOIN TB_R_MOULDING ON TB_R_MOULDING.MOULDING_ID = TB_R_POURING_FLASK.MOULDING_ID
		JOIN TB_M_SYSTEM S ON TB_R_POURING.LADLE_CD = S.SYSTEM_CD AND S.SYSTEM_TYPE = ''LADLE_CD''
		LEFT JOIN TB_M_SYSTEM SS ON TB_R_MOULDING.PRODUCT_TYPE = SS.SYSTEM_CD AND SS.SYSTEM_TYPE = ''PRODUCT_TYPE''
		LEFT JOIN TB_M_SYSTEM SSS ON TB_R_MELTING.SHIFT_CD = SSS.SYSTEM_CD AND SSS.SYSTEM_TYPE = ''SHIFT_CD''
		LEFT JOIN TB_M_SYSTEM SSSS ON TB_R_MELTING.SHIFT_TYPE = SSSS.SYSTEM_CD AND SSSS.SYSTEM_TYPE = ''SHIFT_TYPE''
		WHERE 
		' + @@where + '
		GROUP BY 
		TB_R_MELTING.PRODUCTION_DT
		, TB_R_POURING.POURING_ID
		, TB_R_POURING.FINAL_JUDGEMENT
		, TB_R_MELTING.TAPPING_NO
		, TB_R_POURING.START_POURING
		, TB_R_MELTING.FURNACE_CD
		, TB_R_POURING.LADLE_CD
		, TB_R_POURING.TEMPERATURE
		, TB_R_POURING.TOTAL_POURING_TIME
		, TB_R_MELTING.PRODUCT_TYPE
		, TB_R_POURING.CHILL_TEST
		, TB_R_POURING_FLASK.LOT_NO
		, TB_M_USER.NAME
		, TB_R_POURING_FLASK.POURING_FLASK_ID
		, TB_R_POURING_FLASK.FLASK_STS
		, TB_R_MOULDING.PRODUCT_TYPE
		, TB_R_MELTING.SHIFT_CD
		, TB_R_MELTING.SHIFT_TYPE
		, S.SYSTEM_VALUE
		, SS.SYSTEM_VALUE
		, SSS.SYSTEM_VALUE
		, SSSS.SYSTEM_VALUE
	) TMP
';
INSERT INTO #T1 (
RN, PRODUCTION_DT, POURING_ID, FINAL_JUDGEMENT, TAPPING_NO, START_POURING, FURNACE_CD, LADLE_CD, LADLE_NM, TEMPERATURE, TOTAL_POURING_TIME
, MOLTEN_METAL, CHILL_TEST, LOT_NO, NAME, FLASK_STS, PRODUCT_TYPE, PRODUCT_TYPE_NM, FLASK_NO, SHIFT_CD, SHIFT_CD_NM, SHIFT_TYPE, SHIFT_TYPE_NM
)
exec(@@SQL);

INSERT INTO #T2(PRODUCTION_DT, SHIFT_CD, SHIFT_CD_NM)
SELECT PRODUCTION_DT, SHIFT_CD, SHIFT_CD_NM
FROM #T1
GROUP BY PRODUCTION_DT, TAPPING_NO, START_POURING, FURNACE_CD, LADLE_CD, TEMPERATURE, TOTAL_POURING_TIME, MOLTEN_METAL
	, CHILL_TEST, NAME, FINAL_JUDGEMENT, SHIFT_CD, SHIFT_CD_NM;

	IF @_TYPE = 'HEADER'
	BEGIN
		SELECT LEFT(PRODUCTION_DT, 7) AS PRODUCTION_MT, SHIFT_CD
		, (SELECT REPLACE(REPLACE(REPLACE(SYSTEM_REMARK, '{shift}', CASE SHIFT_CD WHEN 'R' THEN 'Red' WHEN 'W' THEN 'White' END ), '{month}'
		, CASE MONTH(PRODUCTION_DT) 
			WHEN 1 THEN 'Januari' 
			WHEN 2 THEN 'Februari' 
			WHEN 3 THEN 'Maret' 
			WHEN 4 THEN 'April' 
			WHEN 5 THEN 'Mei' 
			WHEN 6 THEN 'Juni' 
			WHEN 7 THEN 'Juli' 
			WHEN 8 THEN 'Agustus' 
			WHEN 9 THEN 'September' 
			WHEN 10 THEN 'Oktober' 
			WHEN 11 THEN 'November' 
			WHEN 12 THEN 'Desember' 
			ELSE '' END 
		)
		, '{year}', YEAR(PRODUCTION_DT)) FROM TB_M_SYSTEM WHERE SYSTEM_TYPE = 'REPORT_LIST' AND SYSTEM_CD = 'POUR_ASPNETMVC3TDKR12') AS REPORT_NAME
		, SHIFT_CD_NM
		FROM #T2 
		GROUP BY  LEFT(PRODUCTION_DT, 7), SHIFT_CD, MONTH(PRODUCTION_DT), YEAR(PRODUCTION_DT), SHIFT_CD_NM
		ORDER BY LEFT(PRODUCTION_DT, 7);

	END
	ELSE
	BEGIN
		SELECT 
			DISTINCT 
			#T1.PRODUCTION_DT
			, COALESCE(DATEDIFF(MINUTE, CAST((SELECT MIN(CASE WHEN FINAL_JUDGEMENT = 1 THEN CAST(START_POURING AS time) END) FROM #T1 T WHERE T.PRODUCTION_DT = #T1.PRODUCTION_DT) AS time), CAST((SELECT MAX(CASE WHEN FINAL_JUDGEMENT = 1 THEN CAST(START_POURING AS time) END) FROM #T1 T WHERE T.PRODUCTION_DT = #T1.PRODUCTION_DT) AS time)) - 45 - 20 
			- CASE WHEN CAST((SELECT MAX(CASE WHEN FINAL_JUDGEMENT = 1 THEN CAST(START_POURING AS time) END) FROM #T1 T WHERE T.PRODUCTION_DT = #T1.PRODUCTION_DT) AS time) >= CAST('18:00' AS time) THEN 15 ELSE 0 END, 0)
			AS PRODUCTION_TM
			--, COALESCE((SELECT CYCLE_TIME FROM TB_R_POURING_SHIFT_SUM WHERE PRODUCTION_DT=#T1.PRODUCTION_DT AND SHIFT_CD = #T1.SHIFT_CD), 0) AS CYCLE_TIME
			--, FORMAT(PRODUCTION_DT, 'dd MMMM yyyy') AS PRODUCTION_DT_NM
			--, DATENAME(WEEKDAY, PRODUCTION_DT) AS DAY_NAME
			--, CASE DATENAME(WEEKDAY, PRODUCTION_DT) 
			--	WHEN 'Monday' THEN 'Senin'
			--	WHEN 'Tuesday' THEN 'Selasa'
			--	WHEN 'Wednesday' THEN 'Rabu'
			--	WHEN 'Thursday' THEN 'Kamis'
			--	WHEN 'Friday' THEN 'Jum''at'
			--	WHEN 'Saturday' THEN 'Sabtu'
			--	WHEN 'Sunday' THEN 'Minggu'
			--END AS DAY_NAME_IDN
			, CASE SHIFT_TYPE
				WHEN 'DAY' THEN 7.58
				WHEN 'NIGHT' THEN 6.58
			END AS SHIFT_TYPE_HOUR
			, CASE SHIFT_TYPE
				WHEN 'DAY' THEN 455
				WHEN 'NIGHT' THEN 395
			END AS SHIFT_TYPE_MINUTE
			--, (SELECT COUNT(1) FROM #T2 WHERE #T2.PRODUCTION_DT = #T1.PRODUCTION_DT) AS PRODUCTION_DT_CNT

			, COALESCE((SELECT MIN(CASE WHEN FINAL_JUDGEMENT = 1 AND MOLTEN_METAL = 'FC' THEN TEMPERATURE END) FROM #T1 T WHERE T.PRODUCTION_DT = #T1.PRODUCTION_DT), 0) AS TEMPERATURE_FC_MIN	
			, COALESCE((SELECT MAX(CASE WHEN FINAL_JUDGEMENT = 1 AND MOLTEN_METAL = 'FC' THEN TEMPERATURE END) FROM #T1 T WHERE T.PRODUCTION_DT = #T1.PRODUCTION_DT), 0) AS TEMPERATURE_FC_MAX
			, COALESCE((SELECT CAST(AVG(CASE WHEN FINAL_JUDGEMENT = 1 AND MOLTEN_METAL = 'FC' THEN TEMPERATURE END) AS DECIMAL(18, 2)) FROM #T1 T WHERE T.PRODUCTION_DT = #T1.PRODUCTION_DT), 0) AS TEMPERATURE_FC_AVG	
			, COALESCE((SELECT MIN(CASE WHEN FINAL_JUDGEMENT = 1 AND MOLTEN_METAL = 'FC' THEN TOTAL_POURING_TIME END) FROM #T1 T WHERE T.PRODUCTION_DT = #T1.PRODUCTION_DT), 0) AS TOTAL_POURING_TIME_FC_MIN	
			, COALESCE((SELECT MAX(CASE WHEN FINAL_JUDGEMENT = 1 AND MOLTEN_METAL = 'FC' THEN TOTAL_POURING_TIME END) FROM #T1 T WHERE T.PRODUCTION_DT = #T1.PRODUCTION_DT), 0) AS TOTAL_POURING_TIME_FC_MAX
			, COALESCE((SELECT CAST(AVG(CASE WHEN FINAL_JUDGEMENT = 1 AND MOLTEN_METAL = 'FC' THEN TOTAL_POURING_TIME END) AS DECIMAL(18, 2)) FROM #T1 T WHERE T.PRODUCTION_DT = #T1.PRODUCTION_DT), 0) AS TOTAL_POURING_TIME_FC_AVG
	
			, (SELECT MIN(CASE WHEN FINAL_JUDGEMENT = 1 AND MOLTEN_METAL = 'FCD' THEN TEMPERATURE END) FROM #T1 T WHERE T.PRODUCTION_DT = #T1.PRODUCTION_DT) AS TEMPERATURE_FCD_MIN	
			, (SELECT MAX(CASE WHEN FINAL_JUDGEMENT = 1 AND MOLTEN_METAL = 'FCD' THEN TEMPERATURE END) FROM #T1 T WHERE T.PRODUCTION_DT = #T1.PRODUCTION_DT) AS TEMPERATURE_FCD_MAX
			, (SELECT CAST(AVG(CASE WHEN FINAL_JUDGEMENT = 1 AND MOLTEN_METAL = 'FCD' THEN TEMPERATURE END) AS DECIMAL(18, 2)) FROM #T1 T WHERE T.PRODUCTION_DT = #T1.PRODUCTION_DT) AS TEMPERATURE_FCD_AVG
			, (SELECT MIN(CASE WHEN FINAL_JUDGEMENT = 1 AND MOLTEN_METAL = 'FCD' THEN TOTAL_POURING_TIME END) FROM #T1 T WHERE T.PRODUCTION_DT = #T1.PRODUCTION_DT) AS TOTAL_POURING_TIME_FCD_MIN		
			, (SELECT MAX(CASE WHEN FINAL_JUDGEMENT = 1 AND MOLTEN_METAL = 'FCD' THEN TOTAL_POURING_TIME END) FROM #T1 T WHERE T.PRODUCTION_DT = #T1.PRODUCTION_DT) AS TOTAL_POURING_TIME_FCD_MAX
			, (SELECT CAST(AVG(CASE WHEN FINAL_JUDGEMENT = 1 AND MOLTEN_METAL = 'FCD' THEN TOTAL_POURING_TIME END) AS DECIMAL(18, 2)) FROM #T1 T WHERE T.PRODUCTION_DT = #T1.PRODUCTION_DT) AS TOTAL_POURING_TIME_FCD_AVG
	
			, (SELECT MIN(CASE WHEN FINAL_JUDGEMENT = 1 AND MOLTEN_METAL = 'FC' THEN CHILL_TEST END) FROM #T1 T WHERE T.PRODUCTION_DT = #T1.PRODUCTION_DT) AS CHILL_TEST_MIN	
			, (SELECT MAX(CASE WHEN FINAL_JUDGEMENT = 1 AND MOLTEN_METAL = 'FC' THEN CHILL_TEST END) FROM #T1 T WHERE T.PRODUCTION_DT = #T1.PRODUCTION_DT) AS CHILL_TEST_MAX
			, (SELECT CAST(AVG(CASE WHEN FINAL_JUDGEMENT = 1 AND MOLTEN_METAL = 'FC' THEN CHILL_TEST END) AS DECIMAL(18, 2)) FROM #T1 T WHERE T.PRODUCTION_DT = #T1.PRODUCTION_DT) AS CHILL_TEST_AVG	
	
			, #T1.SHIFT_CD
			, SHIFT_CD_NM
			, #T1.SHIFT_TYPE
			, SHIFT_TYPE_NM
			
			, COALESCE((SELECT SYSTEM_VALUE FROM TB_M_SYSTEM WHERE SYSTEM_TYPE = 'REPORT_POURING' AND SYSTEM_CD = 'PIC_RED'), '') AS PIC_RED
			, COALESCE((SELECT SYSTEM_VALUE FROM TB_M_SYSTEM WHERE SYSTEM_TYPE = 'REPORT_POURING' AND SYSTEM_CD = 'PIC_WHITE'), '') AS PIC_WHITE
			, COALESCE((SELECT SYSTEM_VALUE FROM TB_M_SYSTEM WHERE SYSTEM_TYPE = 'REPORT_POURING' AND SYSTEM_CD = 'SH_NAME'), '') AS SECTION_HEAD
			, COALESCE((SELECT SYSTEM_VALUE FROM TB_M_SYSTEM WHERE SYSTEM_TYPE = 'REPORT_POURING' AND SYSTEM_CD = 'LH_NAME'), '') AS LINE_HEAD
			, COALESCE((SELECT SYSTEM_VALUE FROM TB_M_SYSTEM WHERE SYSTEM_TYPE = 'REPORT_POURING' AND SYSTEM_CD = 'GH_NAME'), '') AS GROUP_HEAD

			, (SELECT CAST(SYSTEM_VALUE AS decimal(18,2)) FROM TB_M_SYSTEM WHERE SYSTEM_TYPE = 'REPORT_POURING' AND SYSTEM_CD = '1TR_WEIGHT') AS PRODUCT_TYPE_1_LIQ_WEIGHT
			, (SELECT CAST(SYSTEM_VALUE AS decimal(18,2)) FROM TB_M_SYSTEM WHERE SYSTEM_TYPE = 'REPORT_POURING' AND SYSTEM_CD = '2TR_WEIGHT') AS PRODUCT_TYPE_2_LIQ_WEIGHT
			, (SELECT CAST(SYSTEM_VALUE AS decimal(18,2)) FROM TB_M_SYSTEM WHERE SYSTEM_TYPE = 'REPORT_POURING' AND SYSTEM_CD = 'CAMS_WEIGHT') AS PRODUCT_TYPE_3_LIQ_WEIGHT
			, (SELECT CAST(SYSTEM_VALUE AS decimal(18,2)) FROM TB_M_SYSTEM WHERE SYSTEM_TYPE = 'REPORT_POURING' AND SYSTEM_CD = 'CRANK_WEIGHT') AS PRODUCT_TYPE_4_LIQ_WEIGHT
	
			, (SELECT COUNT(1) FROM #T1 T WHERE T.PRODUCTION_DT = #T1.PRODUCTION_DT AND T.FLASK_STS = 1 AND FINAL_JUDGEMENT = 1) AS OK_ALL_CNT
			, (SELECT COUNT(1) FROM #T1 T WHERE T.PRODUCTION_DT = #T1.PRODUCTION_DT AND T.FLASK_STS = 2 AND FINAL_JUDGEMENT = 1) AS NG_ALL_CNT

			, CONCAT(#T1.SHIFT_CD, '_', LEFT(#T1.PRODUCTION_DT, 7)) AS PRODUCTION_MT, RIGHT(#T1.PRODUCTION_DT, 2) AS SHEET_NM, TAPPING_NO
			, CASE WHEN FINAL_JUDGEMENT = 1 THEN START_POURING END AS START_POURING
			, CASE WHEN FINAL_JUDGEMENT = 1 THEN FURNACE_CD END AS FURNACE_CD
			, CASE WHEN FINAL_JUDGEMENT = 1 THEN LADLE_CD END AS LADLE_CD
			, CASE WHEN FINAL_JUDGEMENT = 1 THEN LADLE_NM END AS LADLE_NM
			, CASE WHEN FINAL_JUDGEMENT = 1 THEN TEMPERATURE END AS TEMPERATURE
			, CASE WHEN FINAL_JUDGEMENT = 1 THEN TOTAL_POURING_TIME END AS TOTAL_POURING_TIME
			, CASE WHEN FINAL_JUDGEMENT = 1 THEN MOLTEN_METAL END AS MOLTEN_METAL
			--, CASE WHEN FINAL_JUDGEMENT = 1 THEN CHILL_TEST	END AS CHILL_TEST	
			, CHILL_TEST	
			, CASE WHEN FINAL_JUDGEMENT = 1 THEN 
				COALESCE(stuff((
					select ',' + t.PRODUCT_TYPE
					from #T1 t
					where t.PRODUCTION_DT = #T1.PRODUCTION_DT AND t.TAPPING_NO = #T1.TAPPING_NO AND t.FLASK_STS = 1
					GROUP BY t.PRODUCTION_DT, t.TAPPING_NO, t.PRODUCT_TYPE, t.LOT_NO		
					ORDER BY t.PRODUCT_TYPE
					for xml path('')
				),1,1,''), '') 
			END AS OK_PRODUCT_TYPE
			, CASE WHEN FINAL_JUDGEMENT = 1 THEN 
				COALESCE(stuff((
					select ',' + CAST(t.LOT_NO AS VARCHAR)
					from #T1 t
					where t.PRODUCTION_DT = #T1.PRODUCTION_DT AND t.TAPPING_NO = #T1.TAPPING_NO
					GROUP BY t.PRODUCTION_DT, t.TAPPING_NO, t.PRODUCT_TYPE, t.LOT_NO
					ORDER BY t.PRODUCT_TYPE
					for xml path('')
				),1,1,''), '') 
				END as OK_LOT_NO
			, CASE WHEN FINAL_JUDGEMENT = 1 THEN 
				COALESCE(stuff((
					select ',' + CAST(COUNT(1) AS VARCHAR)
					from #T1 t
					where t.PRODUCTION_DT = #T1.PRODUCTION_DT AND t.TAPPING_NO = #T1.TAPPING_NO AND t.FLASK_STS = 1			
					GROUP BY t.PRODUCTION_DT, t.TAPPING_NO, t.PRODUCT_TYPE, t.LOT_NO
					ORDER BY t.PRODUCT_TYPE
					for xml path('')
				),1,1,''), '')  
			END as OK_CNT	
	
			, (SELECT COUNT(DISTINCT CONCAT(PRODUCTION_DT,TAPPING_NO,LOT_NO)) FROM #T1 t WHERE t.PRODUCTION_DT = #T1.PRODUCTION_DT AND t.FLASK_STS = 1 AND t.PRODUCT_TYPE = 1 AND t.FINAL_JUDGEMENT = 1) AS OK_PRODUCT_1_CNT
			, (SELECT COUNT(DISTINCT CONCAT(PRODUCTION_DT,TAPPING_NO,LOT_NO)) FROM #T1 t WHERE t.PRODUCTION_DT = #T1.PRODUCTION_DT AND t.FLASK_STS = 1 AND t.PRODUCT_TYPE = 2 AND t.FINAL_JUDGEMENT = 1) AS OK_PRODUCT_2_CNT
			, (SELECT COUNT(DISTINCT CONCAT(PRODUCTION_DT,TAPPING_NO,LOT_NO)) FROM #T1 t WHERE t.PRODUCTION_DT = #T1.PRODUCTION_DT AND t.FLASK_STS = 1 AND t.PRODUCT_TYPE = 3 AND t.FINAL_JUDGEMENT = 1) AS OK_PRODUCT_3_CNT
			, (SELECT COUNT(DISTINCT CONCAT(PRODUCTION_DT,TAPPING_NO,LOT_NO)) FROM #T1 t WHERE t.PRODUCTION_DT = #T1.PRODUCTION_DT AND t.FLASK_STS = 1 AND t.PRODUCT_TYPE = 4 AND t.FINAL_JUDGEMENT = 1) AS OK_PRODUCT_4_CNT
			, (SELECT COUNT(1) FROM #T1 t WHERE t.PRODUCTION_DT = #T1.PRODUCTION_DT AND t.FLASK_STS = 1 AND t.PRODUCT_TYPE = 1 AND t.FINAL_JUDGEMENT = 1) AS OK_PRODUCT_1_SUM
			, (SELECT COUNT(1) FROM #T1 t WHERE t.PRODUCTION_DT = #T1.PRODUCTION_DT AND t.FLASK_STS = 1 AND t.PRODUCT_TYPE = 2 AND t.FINAL_JUDGEMENT = 1) AS OK_PRODUCT_2_SUM
			, (SELECT COUNT(1) FROM #T1 t WHERE t.PRODUCTION_DT = #T1.PRODUCTION_DT AND t.FLASK_STS = 1 AND t.PRODUCT_TYPE = 3 AND t.FINAL_JUDGEMENT = 1) AS OK_PRODUCT_3_SUM
			, (SELECT COUNT(1) FROM #T1 t WHERE t.PRODUCTION_DT = #T1.PRODUCTION_DT AND t.FLASK_STS = 1 AND t.PRODUCT_TYPE = 4 AND t.FINAL_JUDGEMENT = 1) AS OK_PRODUCT_4_SUM
			
			, NAME
			, CASE WHEN FINAL_JUDGEMENT = 1 THEN 
				COALESCE(CONCAT(
					CAST(COUNT(CASE WHEN FLASK_STS = 2 AND FLASK_NO = 1 THEN 1 END) AS VARCHAR)
					, ','
					, CAST(COUNT(CASE WHEN FLASK_STS = 2 AND FLASK_NO = 2 THEN 1 END) AS VARCHAR)
					, ','
					, CAST(COUNT(CASE WHEN FLASK_STS = 2 AND FLASK_NO = 3 THEN 1 END) AS VARCHAR)
				), '')
			END AS NG_CNT
			, CASE WHEN FINAL_JUDGEMENT = 1 THEN 
				COALESCE(CONCAT(
					COALESCE((
					select TOP 1 t.PRODUCT_TYPE_NM
					from #T1 t
					where t.PRODUCTION_DT = #T1.PRODUCTION_DT AND t.TAPPING_NO = #T1.TAPPING_NO AND t.FLASK_STS = 2					AND t.FLASK_NO = 1
					), ' ')
					, ','
					, COALESCE((
					select TOP 1 t.PRODUCT_TYPE_NM
					from #T1 t
					where t.PRODUCTION_DT = #T1.PRODUCTION_DT AND t.TAPPING_NO = #T1.TAPPING_NO AND t.FLASK_STS = 2					AND t.FLASK_NO = 2
					), ' ')
					, ','
					, COALESCE((
					select TOP 1 t.PRODUCT_TYPE_NM
					from #T1 t
					where t.PRODUCTION_DT = #T1.PRODUCTION_DT AND t.TAPPING_NO = #T1.TAPPING_NO AND t.FLASK_STS = 2					AND t.FLASK_NO = 3
					), ' ')
				), '')
			END AS NG_MODEL
			, CASE WHEN FINAL_JUDGEMENT = 1 THEN 
				COALESCE(CONCAT(
					COALESCE((
					select DISTINCT TOP 1 CAST(t.LOT_NO AS VARCHAR)
					from #T1 t
					where t.PRODUCTION_DT = #T1.PRODUCTION_DT AND t.TAPPING_NO = #T1.TAPPING_NO AND t.FLASK_STS = 2					AND t.FLASK_NO = 1), ' ')
					, ','
					, 
					COALESCE((
					select DISTINCT TOP 1 CAST(t.LOT_NO AS VARCHAR)
					from #T1 t
					where t.PRODUCTION_DT = #T1.PRODUCTION_DT AND t.TAPPING_NO = #T1.TAPPING_NO AND t.FLASK_STS = 2					AND t.FLASK_NO = 2), ' ')
					, ','
					, 
					COALESCE((
					select DISTINCT TOP 1 CAST(t.LOT_NO AS VARCHAR)
					from #T1 t
					where t.PRODUCTION_DT = #T1.PRODUCTION_DT AND t.TAPPING_NO = #T1.TAPPING_NO AND t.FLASK_STS = 2					AND t.FLASK_NO = 3), ' ')
				), '')
			END AS NG_LOT_NO
			, FINAL_JUDGEMENT
			, (SELECT CAST(MIN(CASE WHEN FINAL_JUDGEMENT = 1 THEN CAST(START_POURING AS time) END) AS VARCHAR(5)) FROM #T1 T WHERE T.PRODUCTION_DT = #T1.PRODUCTION_DT) AS POURING_START
			, (SELECT CAST(MAX(CASE WHEN FINAL_JUDGEMENT = 1 THEN CAST(START_POURING AS time) END)  AS VARCHAR(5)) FROM #T1 T WHERE T.PRODUCTION_DT = #T1.PRODUCTION_DT) AS POURING_FINISH
			
			, 0 AS LS_MOULDING
			, 0 AS LS_MELTING
			, 0 AS LS_CORE_MAKING
			, 0 AS LS_OTHER
			, 0 AS LS_TOTAL
			, 0 AS PRODUCTION_EFFICIENCY
			, 0 AS PROD_MURNI
			, 0 AS PROD_UMUM
			, 0 AS PROD_TOTAL
	
			-- 	OPERATOR
			, (SELECT  COUNT(DISTINCT NAME) FROM #T1 t WHERE t.PRODUCTION_DT = #T1.PRODUCTION_DT AND t.SHIFT_CD = #T1.SHIFT_CD) AS OPERATOR_TOTAL_MP
			, 0 AS OPERATOR_CUTI
			, 0 AS OPERATOR_SAKIT
			, 0 AS OPERATOR_IZIN
			, 0 AS OPERATOR_TELAT
			, 0 AS OPERATOR_BANTUAN
			, 0 AS OPERATOR_DIPERBANTUKAN
			, (SELECT  COUNT(DISTINCT NAME) FROM #T1 t WHERE t.PRODUCTION_DT = #T1.PRODUCTION_DT AND t.SHIFT_CD = #T1.SHIFT_CD) AS OPERATOR_MPA
			, 0 AS OPERATOR_MHA
	
			-- 	HEAD
			--, COALESCE((SELECT COUNT(NAME) FROM TB_R_POURING_SHIFT_SUM JOIN TB_M_USER ON TB_M_USER.USER_ID = TB_R_POURING_SHIFT_SUM.GH_LH WHERE TB_R_POURING_SHIFT_SUM.PRODUCTION_DT = #T1.PRODUCTION_DT AND TB_R_POURING_SHIFT_SUM.SHIFT_CD = #T1.SHIFT_CD), '') AS HEAD_TOTAL_MP
			, 0 AS HEAD_CUTI
			, 0 AS HEAD_SAKIT
			, 0 AS HEAD_IZIN
			, 0 AS HEAD_TELAT
			, 0 AS HEAD_BANTUAN
			, 0 AS HEAD_DIPERBANTUKAN
			--, COALESCE((SELECT COUNT(NAME) FROM TB_R_POURING_SHIFT_SUM JOIN TB_M_USER ON TB_M_USER.USER_ID = TB_R_POURING_SHIFT_SUM.GH_LH WHERE TB_R_POURING_SHIFT_SUM.PRODUCTION_DT = #T1.PRODUCTION_DT AND TB_R_POURING_SHIFT_SUM.SHIFT_CD = #T1.SHIFT_CD), '') AS HEAD_MPA
			, 0 AS HEAD_MHA
	
			, COALESCE((SELECT POURING_SHIFT_ID FROM TB_R_POURING_SHIFT_SUM WHERE TB_R_POURING_SHIFT_SUM.PRODUCTION_DT = #T1.PRODUCTION_DT AND TB_R_POURING_SHIFT_SUM.SHIFT_CD = #T1.SHIFT_CD), null) AS POURING_SHIFT_ID
			--, COALESCE((SELECT A2 FROM TB_R_POURING_SHIFT_SUM WHERE TB_R_POURING_SHIFT_SUM.PRODUCTION_DT = #T1.PRODUCTION_DT AND TB_R_POURING_SHIFT_SUM.SHIFT_CD = #T1.SHIFT_CD), 0) AS OT_A2
			--, COALESCE((SELECT B2 FROM TB_R_POURING_SHIFT_SUM WHERE TB_R_POURING_SHIFT_SUM.PRODUCTION_DT = #T1.PRODUCTION_DT AND TB_R_POURING_SHIFT_SUM.SHIFT_CD = #T1.SHIFT_CD), 0) AS OT_B2
			--, COALESCE((SELECT C2 FROM TB_R_POURING_SHIFT_SUM WHERE TB_R_POURING_SHIFT_SUM.PRODUCTION_DT = #T1.PRODUCTION_DT AND TB_R_POURING_SHIFT_SUM.SHIFT_CD = #T1.SHIFT_CD), 0) AS OT_C2
			--, COALESCE((SELECT D2 FROM TB_R_POURING_SHIFT_SUM WHERE TB_R_POURING_SHIFT_SUM.PRODUCTION_DT = #T1.PRODUCTION_DT AND TB_R_POURING_SHIFT_SUM.SHIFT_CD = #T1.SHIFT_CD), 0) AS OT_D2
			--, COALESCE((SELECT E2 FROM TB_R_POURING_SHIFT_SUM WHERE TB_R_POURING_SHIFT_SUM.PRODUCTION_DT = #T1.PRODUCTION_DT AND TB_R_POURING_SHIFT_SUM.SHIFT_CD = #T1.SHIFT_CD), 0) AS OT_E2
			--, COALESCE((SELECT F2 FROM TB_R_POURING_SHIFT_SUM WHERE TB_R_POURING_SHIFT_SUM.PRODUCTION_DT = #T1.PRODUCTION_DT AND TB_R_POURING_SHIFT_SUM.SHIFT_CD = #T1.SHIFT_CD), 0) AS OT_F2
			--, COALESCE((SELECT G2 FROM TB_R_POURING_SHIFT_SUM WHERE TB_R_POURING_SHIFT_SUM.PRODUCTION_DT = #T1.PRODUCTION_DT AND TB_R_POURING_SHIFT_SUM.SHIFT_CD = #T1.SHIFT_CD), 0) AS OT_G2
			--, COALESCE((SELECT H2 FROM TB_R_POURING_SHIFT_SUM WHERE TB_R_POURING_SHIFT_SUM.PRODUCTION_DT = #T1.PRODUCTION_DT AND TB_R_POURING_SHIFT_SUM.SHIFT_CD = #T1.SHIFT_CD), 0) AS OT_H2
			--, COALESCE((SELECT I2 FROM TB_R_POURING_SHIFT_SUM WHERE TB_R_POURING_SHIFT_SUM.PRODUCTION_DT = #T1.PRODUCTION_DT AND TB_R_POURING_SHIFT_SUM.SHIFT_CD = #T1.SHIFT_CD), 0) AS OT_I2
			--, COALESCE((SELECT J2 FROM TB_R_POURING_SHIFT_SUM WHERE TB_R_POURING_SHIFT_SUM.PRODUCTION_DT = #T1.PRODUCTION_DT AND TB_R_POURING_SHIFT_SUM.SHIFT_CD = #T1.SHIFT_CD), 0) AS OT_J2
			--, COALESCE((SELECT CAST(NOTES AS VARCHAR(MAX)) FROM TB_R_POURING_SHIFT_SUM WHERE TB_R_POURING_SHIFT_SUM.PRODUCTION_DT = #T1.PRODUCTION_DT AND TB_R_POURING_SHIFT_SUM.SHIFT_CD = #T1.SHIFT_CD), '') AS NOTES
			, 0 AS OT_TOTAL
	
			, 0 AS MHM
			, 0 AS MHU
			, 0 AS MHT

			--, COALESCE((SELECT START_BURNER_WEST FROM TB_R_POURING_SHIFT_SUM WHERE TB_R_POURING_SHIFT_SUM.PRODUCTION_DT = #T1.PRODUCTION_DT AND TB_R_POURING_SHIFT_SUM.SHIFT_CD = #T1.SHIFT_CD), 0) AS START_BURNER_WEST
			--, COALESCE((SELECT FINISH_BURNER_WEST FROM TB_R_POURING_SHIFT_SUM WHERE TB_R_POURING_SHIFT_SUM.PRODUCTION_DT = #T1.PRODUCTION_DT AND TB_R_POURING_SHIFT_SUM.SHIFT_CD = #T1.SHIFT_CD), 0) AS FINISH_BURNER_WEST
			--, COALESCE((SELECT START_BURNER_EAST FROM TB_R_POURING_SHIFT_SUM WHERE TB_R_POURING_SHIFT_SUM.PRODUCTION_DT = #T1.PRODUCTION_DT AND TB_R_POURING_SHIFT_SUM.SHIFT_CD = #T1.SHIFT_CD), 0) AS START_BURNER_EAST
			--, COALESCE((SELECT FINISH_BURNER_EAST FROM TB_R_POURING_SHIFT_SUM WHERE TB_R_POURING_SHIFT_SUM.PRODUCTION_DT = #T1.PRODUCTION_DT AND TB_R_POURING_SHIFT_SUM.SHIFT_CD = #T1.SHIFT_CD), 0) AS FINISH_BURNER_EAST

		FROM #T1
		GROUP BY #T1.PRODUCTION_DT, TAPPING_NO, START_POURING, FURNACE_CD, LADLE_CD, LADLE_NM, TEMPERATURE, TOTAL_POURING_TIME, MOLTEN_METAL
			, CHILL_TEST, NAME, FINAL_JUDGEMENT, #T1.SHIFT_CD, SHIFT_CD_NM, #T1.SHIFT_TYPE, SHIFT_TYPE_NM
		ORDER BY #T1.PRODUCTION_DT;
	END


IF OBJECT_ID(N'tempdb..#T1') IS NOT NULL
BEGIN
	DROP TABLE #T1
END
IF OBJECT_ID(N'tempdb..#T2') IS NOT NULL
BEGIN
	DROP TABLE #T2
END
