
IF OBJECT_ID(N'tempdb..#T_CAMS') IS NOT NULL
BEGIN
	DROP TABLE #T_CAMS
END
CREATE TABLE #T_CAMS
(
	MELTING_ID	int
	, PRODUCTION_DT	date
	, SHIFT_CD	varchar(20)
	, MATERIAL_C decimal(18, 2)
	, MATERIAL_SI decimal(18, 2)
	, MATERIAL_MN decimal(18, 2)
	, MATERIAL_P decimal(18, 2)
	, MATERIAL_S decimal(18, 2)
	, MATERIAL_CR decimal(18, 2)
	, MATERIAL_MG decimal(18, 2)
	, MATERIAL_SB decimal(18, 2)
	, MATERIAL_ZN decimal(18, 2)
	, MATERIAL_CE decimal(18, 2)
	, MATERIAL_MO decimal(18, 2)
	, MATERIAL_NI decimal(18, 2)
	, MATERIAL_SN decimal(18, 2)
	, MATERIAL_CU decimal(18, 2)
);
INSERT INTO #T_CAMS(MELTING_ID, PRODUCTION_DT, SHIFT_CD)
SELECT DISTINCT MELTING_ID, PRODUCTION_DT, SHIFT_CD FROM TB_R_CAMS WHERE MELTING_ID = @_MELTING_ID;

UPDATE #T_CAMS
	SET MATERIAL_C = X.MATERIAL_C
	FROM #T_CAMS
	JOIN (SELECT * FROM
	(SELECT 
		ROW_NUMBER() OVER (
		PARTITION BY TB_R_CAMS.MELTING_ID
		ORDER BY TB_R_CAMS.CAM_ID
		) AS RN, MELTING_ID, PRODUCTION_DT, SHIFT_CD, MATERIAL_C FROM TB_R_CAMS WHERE MATERIAL_C_STS = 1 AND MELTING_ID = @_MELTING_ID
	)TMP 
WHERE RN=1)X ON X.MELTING_ID= #T_CAMS.MELTING_ID;

UPDATE #T_CAMS
	SET MATERIAL_SI = X.MATERIAL_SI
	FROM #T_CAMS
	JOIN (SELECT * FROM
	(SELECT 
		ROW_NUMBER() OVER (
		PARTITION BY TB_R_CAMS.MELTING_ID
		ORDER BY TB_R_CAMS.CAM_ID
		) AS RN, MELTING_ID, PRODUCTION_DT, SHIFT_CD, MATERIAL_SI FROM TB_R_CAMS WHERE MATERIAL_SI_STS = 1 AND MELTING_ID = @_MELTING_ID
	)TMP 
WHERE RN=1)X ON X.MELTING_ID= #T_CAMS.MELTING_ID;

UPDATE #T_CAMS
	SET MATERIAL_MN = X.MATERIAL_MN
	FROM #T_CAMS
	JOIN (SELECT * FROM
	(SELECT 
		ROW_NUMBER() OVER (
		PARTITION BY TB_R_CAMS.MELTING_ID
		ORDER BY TB_R_CAMS.CAM_ID
		) AS RN, MELTING_ID, PRODUCTION_DT, SHIFT_CD, MATERIAL_MN FROM TB_R_CAMS WHERE MATERIAL_MN_STS = 1 AND MELTING_ID = @_MELTING_ID
	)TMP 
WHERE RN=1)X ON X.MELTING_ID= #T_CAMS.MELTING_ID;

UPDATE #T_CAMS
	SET MATERIAL_P = X.MATERIAL_P
	FROM #T_CAMS
	JOIN (SELECT * FROM
	(SELECT 
		ROW_NUMBER() OVER (
		PARTITION BY TB_R_CAMS.MELTING_ID
		ORDER BY TB_R_CAMS.CAM_ID
		) AS RN, MELTING_ID, PRODUCTION_DT, SHIFT_CD, MATERIAL_P FROM TB_R_CAMS WHERE MATERIAL_P_STS = 1 AND MELTING_ID = @_MELTING_ID
	)TMP 
WHERE RN=1)X ON X.MELTING_ID= #T_CAMS.MELTING_ID;

UPDATE #T_CAMS
	SET MATERIAL_S = X.MATERIAL_S
	FROM #T_CAMS
	JOIN (SELECT * FROM
	(SELECT 
		ROW_NUMBER() OVER (
		PARTITION BY TB_R_CAMS.MELTING_ID
		ORDER BY TB_R_CAMS.CAM_ID
		) AS RN, MELTING_ID, PRODUCTION_DT, SHIFT_CD, MATERIAL_S FROM TB_R_CAMS WHERE MATERIAL_S_STS = 1 AND MELTING_ID = @_MELTING_ID
	)TMP 
WHERE RN=1)X ON X.MELTING_ID= #T_CAMS.MELTING_ID;

UPDATE #T_CAMS
	SET MATERIAL_CR = X.MATERIAL_CR
	FROM #T_CAMS
	JOIN (SELECT * FROM
	(SELECT 
		ROW_NUMBER() OVER (
		PARTITION BY TB_R_CAMS.MELTING_ID
		ORDER BY TB_R_CAMS.CAM_ID
		) AS RN, MELTING_ID, PRODUCTION_DT, SHIFT_CD, MATERIAL_CR FROM TB_R_CAMS WHERE MATERIAL_CR_STS = 1 AND MELTING_ID = @_MELTING_ID
	)TMP 
WHERE RN=1)X ON X.MELTING_ID= #T_CAMS.MELTING_ID;

UPDATE #T_CAMS
	SET MATERIAL_MG = X.MATERIAL_MG
	FROM #T_CAMS
	JOIN (SELECT * FROM
	(SELECT 
		ROW_NUMBER() OVER (
		PARTITION BY TB_R_CAMS.MELTING_ID
		ORDER BY TB_R_CAMS.CAM_ID
		) AS RN, MELTING_ID, PRODUCTION_DT, SHIFT_CD, MATERIAL_MG FROM TB_R_CAMS WHERE MATERIAL_MG_STS = 1 AND MELTING_ID = @_MELTING_ID
	)TMP 
WHERE RN=1)X ON X.MELTING_ID= #T_CAMS.MELTING_ID;

UPDATE #T_CAMS
	SET MATERIAL_SB = X.MATERIAL_SB
	FROM #T_CAMS
	JOIN (SELECT * FROM
	(SELECT 
		ROW_NUMBER() OVER (
		PARTITION BY TB_R_CAMS.MELTING_ID
		ORDER BY TB_R_CAMS.CAM_ID
		) AS RN, MELTING_ID, PRODUCTION_DT, SHIFT_CD, MATERIAL_SB FROM TB_R_CAMS WHERE MATERIAL_SB_STS = 1 AND MELTING_ID = @_MELTING_ID
	)TMP 
WHERE RN=1)X ON X.MELTING_ID= #T_CAMS.MELTING_ID;

UPDATE #T_CAMS
	SET MATERIAL_ZN = X.MATERIAL_ZN
	FROM #T_CAMS
	JOIN (SELECT * FROM
	(SELECT 
		ROW_NUMBER() OVER (
		PARTITION BY TB_R_CAMS.MELTING_ID
		ORDER BY TB_R_CAMS.CAM_ID
		) AS RN, MELTING_ID, PRODUCTION_DT, SHIFT_CD, MATERIAL_ZN FROM TB_R_CAMS WHERE MATERIAL_ZN_STS = 1 AND MELTING_ID = @_MELTING_ID
	)TMP 
WHERE RN=1)X ON X.MELTING_ID= #T_CAMS.MELTING_ID;

UPDATE #T_CAMS
	SET MATERIAL_CE = X.MATERIAL_CE
	FROM #T_CAMS
	JOIN (SELECT * FROM
	(SELECT 
		ROW_NUMBER() OVER (
		PARTITION BY TB_R_CAMS.MELTING_ID
		ORDER BY TB_R_CAMS.CAM_ID
		) AS RN, MELTING_ID, PRODUCTION_DT, SHIFT_CD, MATERIAL_CE FROM TB_R_CAMS WHERE MATERIAL_CE_STS = 1 AND MELTING_ID = @_MELTING_ID
	)TMP 
WHERE RN=1)X ON X.MELTING_ID= #T_CAMS.MELTING_ID;

UPDATE #T_CAMS
	SET MATERIAL_MO = X.MATERIAL_MO
	FROM #T_CAMS
	JOIN (SELECT * FROM
	(SELECT 
		ROW_NUMBER() OVER (
		PARTITION BY TB_R_CAMS.MELTING_ID
		ORDER BY TB_R_CAMS.CAM_ID
		) AS RN, MELTING_ID, PRODUCTION_DT, SHIFT_CD, MATERIAL_MO FROM TB_R_CAMS WHERE MATERIAL_MO_STS = 1 AND MELTING_ID = @_MELTING_ID
	)TMP 
WHERE RN=1)X ON X.MELTING_ID= #T_CAMS.MELTING_ID;

UPDATE #T_CAMS
	SET MATERIAL_NI = X.MATERIAL_NI
	FROM #T_CAMS
	JOIN (SELECT * FROM
	(SELECT 
		ROW_NUMBER() OVER (
		PARTITION BY TB_R_CAMS.MELTING_ID
		ORDER BY TB_R_CAMS.CAM_ID
		) AS RN, MELTING_ID, PRODUCTION_DT, SHIFT_CD, MATERIAL_NI FROM TB_R_CAMS WHERE MATERIAL_NI_STS = 1 AND MELTING_ID = @_MELTING_ID
	)TMP 
WHERE RN=1)X ON X.MELTING_ID= #T_CAMS.MELTING_ID;

UPDATE #T_CAMS
	SET MATERIAL_SN = X.MATERIAL_SN
	FROM #T_CAMS
	JOIN (SELECT * FROM
	(SELECT 
		ROW_NUMBER() OVER (
		PARTITION BY TB_R_CAMS.MELTING_ID
		ORDER BY TB_R_CAMS.CAM_ID
		) AS RN, MELTING_ID, PRODUCTION_DT, SHIFT_CD, MATERIAL_SN FROM TB_R_CAMS WHERE MATERIAL_SN_STS = 1 AND MELTING_ID = @_MELTING_ID
	)TMP 
WHERE RN=1)X ON X.MELTING_ID= #T_CAMS.MELTING_ID;

UPDATE #T_CAMS
	SET MATERIAL_CU = X.MATERIAL_CU
	FROM #T_CAMS
	JOIN (SELECT * FROM
	(SELECT 
		ROW_NUMBER() OVER (
		PARTITION BY TB_R_CAMS.MELTING_ID
		ORDER BY TB_R_CAMS.CAM_ID
		) AS RN, MELTING_ID, PRODUCTION_DT, SHIFT_CD, MATERIAL_CU FROM TB_R_CAMS WHERE MATERIAL_CU_STS = 1 AND MELTING_ID = @_MELTING_ID
	)TMP 
WHERE RN=1)X ON X.MELTING_ID= #T_CAMS.MELTING_ID;

SELECT 
	#T_CAMS.MELTING_ID
	, #T_CAMS.PRODUCTION_DT
	, CASE WHEN 
		#T_CAMS.MATERIAL_C IS NOT NULL
		OR #T_CAMS.MATERIAL_SI IS NOT NULL
		OR #T_CAMS.MATERIAL_MN IS NOT NULL
		OR #T_CAMS.MATERIAL_P IS NOT NULL
		OR #T_CAMS.MATERIAL_CR IS NOT NULL
		OR #T_CAMS.MATERIAL_MG IS NOT NULL
		OR #T_CAMS.MATERIAL_SB IS NOT NULL
		OR #T_CAMS.MATERIAL_ZN IS NOT NULL
		OR #T_CAMS.MATERIAL_CE IS NOT NULL
		OR #T_CAMS.MATERIAL_MO IS NOT NULL 
		OR #T_CAMS.MATERIAL_NI IS NOT NULL
		OR #T_CAMS.MATERIAL_SN IS NOT NULL
		OR #T_CAMS.MATERIAL_CU IS NOT NULL
	THEN 
		CONCAT(
			CASE WHEN #T_CAMS.MATERIAL_C IS NOT NULL THEN CONCAT(', C ', #T_CAMS.MATERIAL_C)  END
			, CASE WHEN #T_CAMS.MATERIAL_SI IS NOT NULL THEN CONCAT(', Si ', #T_CAMS.MATERIAL_SI)  END
			, CASE WHEN #T_CAMS.MATERIAL_MN IS NOT NULL THEN CONCAT(', Mn ', #T_CAMS.MATERIAL_MN)  END
			, CASE WHEN #T_CAMS.MATERIAL_P IS NOT NULL THEN CONCAT(', P ', #T_CAMS.MATERIAL_P)  END
			, CASE WHEN #T_CAMS.MATERIAL_CR IS NOT NULL THEN CONCAT(', Cr ', #T_CAMS.MATERIAL_CR)  END
			, CASE WHEN #T_CAMS.MATERIAL_MG IS NOT NULL THEN CONCAT(', Mg ', #T_CAMS.MATERIAL_MG)  END
			, CASE WHEN #T_CAMS.MATERIAL_SB IS NOT NULL THEN CONCAT(', Sb ', #T_CAMS.MATERIAL_SB)  END
			, CASE WHEN #T_CAMS.MATERIAL_ZN IS NOT NULL THEN CONCAT(', Zn ', #T_CAMS.MATERIAL_ZN)  END
			, CASE WHEN #T_CAMS.MATERIAL_CE IS NOT NULL THEN CONCAT(', Ce ', #T_CAMS.MATERIAL_CE)  END
			, CASE WHEN #T_CAMS.MATERIAL_MO IS NOT NULL THEN CONCAT(', Mo ', #T_CAMS.MATERIAL_MO)  END
			, CASE WHEN #T_CAMS.MATERIAL_NI IS NOT NULL THEN CONCAT(', Ni ', #T_CAMS.MATERIAL_NI)  END
			, CASE WHEN #T_CAMS.MATERIAL_SN IS NOT NULL THEN CONCAT(', Sn ', #T_CAMS.MATERIAL_SN)  END
			, CASE WHEN #T_CAMS.MATERIAL_CU IS NOT NULL THEN CONCAT(', Cu ', #T_CAMS.MATERIAL_CU)  END
		)
	END AS ADJUST
	, #T_CAMS.SHIFT_CD
	, #T_CAMS.MATERIAL_C
	, #T_CAMS.MATERIAL_SI
	, #T_CAMS.MATERIAL_MN
	, #T_CAMS.MATERIAL_P
	, #T_CAMS.MATERIAL_CR
	, #T_CAMS.MATERIAL_MG
	, #T_CAMS.MATERIAL_SB
	, #T_CAMS.MATERIAL_ZN
	, #T_CAMS.MATERIAL_CE
	, #T_CAMS.MATERIAL_MO
	, #T_CAMS.MATERIAL_NI
	, #T_CAMS.MATERIAL_SN
	, #T_CAMS.MATERIAL_CU
FROM #T_CAMS
GROUP BY
	#T_CAMS.MELTING_ID
	, #T_CAMS.PRODUCTION_DT
	, #T_CAMS.SHIFT_CD
	, #T_CAMS.MATERIAL_C
	, #T_CAMS.MATERIAL_SI
	, #T_CAMS.MATERIAL_MN
	, #T_CAMS.MATERIAL_P
	, #T_CAMS.MATERIAL_CR
	, #T_CAMS.MATERIAL_MG
	, #T_CAMS.MATERIAL_SB
	, #T_CAMS.MATERIAL_ZN
	, #T_CAMS.MATERIAL_CE
	, #T_CAMS.MATERIAL_MO
	, #T_CAMS.MATERIAL_NI
	, #T_CAMS.MATERIAL_SN
	, #T_CAMS.MATERIAL_CU

IF OBJECT_ID(N'tempdb..#T_CAMS') IS NOT NULL
BEGIN
	DROP TABLE #T_CAMS
END;