SELECT TB_R_MELTING.PRODUCTION_DT, TB_R_MELTING.SHIFT_CD
, CASE WHEN TB_R_MELTING.PRODUCT_TYPE = 'TR' THEN 'FC' WHEN TB_R_MELTING.PRODUCT_TYPE = 'Crank' OR TB_R_MELTING.PRODUCT_TYPE = 'Camshaft' THEN 'FCD' END AS MOLTEN_METAL
, MIN(MATERIAL_C) AS MATERIAL_C_MIN
, MIN(MATERIAL_SI) AS MATERIAL_SI_MIN
, MIN(MATERIAL_MN) AS MATERIAL_MN_MIN
, MIN(MATERIAL_P) AS MATERIAL_P_MIN
, MIN(MATERIAL_S) AS MATERIAL_S_MIN
, MIN(MATERIAL_CR) AS MATERIAL_CR_MIN
, MIN(MATERIAL_MG) AS MATERIAL_MG_MIN
, MIN(MATERIAL_SB) AS MATERIAL_SB_MIN
, MIN(MATERIAL_ZN) AS MATERIAL_ZN_MIN
, MIN(MATERIAL_CE) AS MATERIAL_CE_MIN
, MIN(MATERIAL_MO) AS MATERIAL_MO_MIN
, MIN(MATERIAL_NI) AS MATERIAL_NI_MIN
, MIN(MATERIAL_SN) AS MATERIAL_SN_MIN
, MIN(MATERIAL_CU) AS MATERIAL_CU_MIN

, MAX(MATERIAL_C) AS MATERIAL_C_MAX
, MAX(MATERIAL_SI) AS MATERIAL_SI_MAX
, MAX(MATERIAL_MN) AS MATERIAL_MN_MAX
, MAX(MATERIAL_P) AS MATERIAL_P_MAX
, MAX(MATERIAL_S) AS MATERIAL_S_MAX
, MAX(MATERIAL_CR) AS MATERIAL_CR_MAX
, MAX(MATERIAL_MG) AS MATERIAL_MG_MAX
, MAX(MATERIAL_SB) AS MATERIAL_SB_MAX
, MAX(MATERIAL_ZN) AS MATERIAL_ZN_MAX
, MAX(MATERIAL_CE) AS MATERIAL_CE_MAX
, MAX(MATERIAL_MO) AS MATERIAL_MO_MAX
, MAX(MATERIAL_NI) AS MATERIAL_NI_MAX
, MAX(MATERIAL_SN) AS MATERIAL_SN_MAX
, MAX(MATERIAL_CU) AS MATERIAL_CU_MAX

, AVG(MATERIAL_C) AS MATERIAL_C_AVG
, AVG(MATERIAL_SI) AS MATERIAL_SI_AVG
, AVG(MATERIAL_MN) AS MATERIAL_MN_AVG
, AVG(MATERIAL_P) AS MATERIAL_P_AVG
, AVG(MATERIAL_S) AS MATERIAL_S_AVG
, AVG(MATERIAL_CR) AS MATERIAL_CR_AVG
, AVG(MATERIAL_MG) AS MATERIAL_MG_AVG
, AVG(MATERIAL_SB) AS MATERIAL_SB_AVG
, AVG(MATERIAL_ZN) AS MATERIAL_ZN_AVG
, AVG(MATERIAL_CE) AS MATERIAL_CE_AVG
, AVG(MATERIAL_MO) AS MATERIAL_MO_AVG
, AVG(MATERIAL_NI) AS MATERIAL_NI_AVG
, AVG(MATERIAL_SN) AS MATERIAL_SN_AVG
, AVG(MATERIAL_CU) AS MATERIAL_CU_AVG
, CAST(MIN(TAPPING_TEMPERATURE) AS decimal(18,2)) AS TAPPING_TEMPERATURE_MIN
, CAST(MAX(TAPPING_TEMPERATURE) AS decimal(18,2)) AS TAPPING_TEMPERATURE_MAX
, CAST(AVG(TAPPING_TEMPERATURE) AS decimal(18,2)) AS TAPPING_TEMPERATURE_AVG
FROM TB_R_MELTING
LEFT JOIN TB_R_CAMS ON TB_R_MELTING.MELTING_ID = TB_R_CAMS.MELTING_ID AND TB_R_CAMS.FINAL_STS = 1

WHERE TB_R_MELTING.PRODUCTION_DT = @_PRODUCTION_DT AND TB_R_MELTING.SHIFT_CD = @_SHIFT_CD
GROUP BY TB_R_MELTING.PRODUCTION_DT, TB_R_MELTING.SHIFT_CD, CASE WHEN TB_R_MELTING.PRODUCT_TYPE = 'TR' THEN 'FC' WHEN TB_R_MELTING.PRODUCT_TYPE = 'Crank' OR TB_R_MELTING.PRODUCT_TYPE = 'Camshaft' THEN 'FCD' END