DECLARE @@USERNAME VARCHAR(50) = @USERNAME;
DECLARE @@ROLE VARCHAR(50) = @ROLE;
DECLARE @@APPALIAS VARCHAR(50) = @APPALIAS;

SELECT A.USERNAME,A.APPLICATION,A.ROLE,B.MENU_ID,B.MENU_TEXT,B.MENU_PARENT,B.GLYPH,B.[TARGET]
,B.IS_ACTIVE,B.[URL],B.VISIBILITY
FROM TB_M_AUTHORIZATION A
right join TB_M_MENU B on B.APP_ID = A.APPLICATION
WHERE A.[FUNCTION] = B.MENU_ID 
AND A.APPLICATION = @@APPALIAS AND USERNAME =@@USERNAME AND B.MENU_PARENT = ''