DECLARE 
    @@QUERY VARCHAR(MAX),
    @@POSITION_LEVEL VARCHAR(MAX) = REPLACE(@P_POSITION_LEVEL, '''', '`'),
    @@POSITION_ABBR VARCHAR(MAX) =  REPLACE(@P_POSITION_ABBR, '''', '`'),
    @@POSITION_DESC VARCHAR(MAX) = REPLACE(@P_POSITION_DESC, '''', '`');

SET @@QUERY = 'SELECT * FROM TB_M_ORG_POSITION WHERE 1=1';

IF(@@POSITION_LEVEL != '')  BEGIN
    SET @@QUERY = @@QUERY + ' AND POSITION_LEVEL  = ''' + @@POSITION_LEVEL + '''';
END;

IF(@@POSITION_ABBR != '')  BEGIN
    SET @@QUERY = @@QUERY + ' AND POSITION_ABBR  = ''' + @@POSITION_ABBR + '''';
END;

IF(@@POSITION_DESC != '')  BEGIN
    SET @@QUERY = @@QUERY + ' AND POSITION_DESC LIKE ''%' + @@POSITION_DESC + '%''';
END;

EXECUTE (@@QUERY);