DECLARE 
	  @@QUERY VARCHAR(MAX)
	, @@LENGTH INT
	, @@PROCESS_DATE_FROM VARCHAR(50)
	, @@PROCESS_DATE_TO VARCHAR(50)
	, @@FUNCTION VARCHAR(50)
	, @@FROMNUMBER INT
	, @@TONUMBER INT
	, @@ORDER_BY VARCHAR(MAX)
	, @@ORDER_TYPE VARCHAR(MAX);
	
	SET @@LENGTH		= @P_LENGTH;
	SET @@PROCESS_DATE_FROM = REPLACE(@P_PROCESS_DATE_FROM, '''', '`');
	SET @@PROCESS_DATE_TO = REPLACE(@P_PROCESS_DATE_TO, '''', '`');
	SET @@FUNCTION		= REPLACE(@P_FUNCTION, '''', '`');
	SET @@FROMNUMBER	= @P_FROMNUMBER;
	SET @@TONUMBER		= @P_TONUMBER;
	SET @@ORDER_BY		= @P_ORDER_BY;
	SET @@ORDER_TYPE	= REPLACE(@P_ORDER_TYPE, '''', '`');
	--SET @@LENGTH		= 20;
	--SET @@PROCESS_DATE_FROM = '23.03.2023';
	--SET @@PROCESS_DATE_TO = '';
	--SET @@FUNCTION		= 'ASPNETMVC3TDKB01';
	--SET @@FROMNUMBER	= 10;
	--SET @@TONUMBER		= 10;
	--SET @@ORDER_BY		= 'PROCESS_ID';
	--SET @@ORDER_TYPE	= REPLACE('ASC', '''', '`');

SET @@QUERY = 'SELECT 
	''CASPER'' AS APPLICATION_NAME,
	PROCESS_ID,
	FUNC_ID,
	PROCESS_STS,
	CONCAT(CONVERT(VARCHAR, PROCESS_START_DT, 104), '' '', CONVERT(VARCHAR, PROCESS_START_DT, 8)) AS PROCESS_START_DT ,
	CONCAT(CONVERT(VARCHAR, PROCESS_END_DT, 104), '' '', CONVERT(VARCHAR, PROCESS_END_DT, 8)) AS PROCESS_END_DT,
	CREATED_BY,
	CONVERT(VARCHAR, CREATED_DT, 104) AS CREATED_DT,
	CHANGED_BY,
	CONVERT(VARCHAR, CHANGED_DT, 104) AS CHANGED_DT
FROM TB_R_LOG_H WHERE 1=1 ';


IF (@@FUNCTION != '') BEGIN
	SET @@QUERY = @@QUERY + ' AND FUNC_ID LIKE ''%' + CONVERT(VARCHAR, @@FUNCTION) + '%''';
END

IF (@@PROCESS_DATE_TO != '') BEGIN
	SET @@PROCESS_DATE_FROM = RIGHT(@@PROCESS_DATE_FROM, 4) + '-' + SUBSTRING(@@PROCESS_DATE_FROM, 4, 2) + '-' + LEFT(@@PROCESS_DATE_FROM, 2);
	SET @@PROCESS_DATE_TO = RIGHT(@@PROCESS_DATE_TO, 4) + '-' + SUBSTRING(@@PROCESS_DATE_TO, 4, 2) + '-' + LEFT(@@PROCESS_DATE_TO, 2);
	SET @@QUERY = @@QUERY + ' AND CAST(PROCESS_START_DT AS DATE) BETWEEN CAST(''' +  @@PROCESS_DATE_FROM + ''' AS DATE) AND CAST(''' + @@PROCESS_DATE_TO +''' AS DATE)';
	--SET @@QUERY = @@QUERY + ' AND CONVERT(VARCHAR, PROCESS_START_DT,104) BETWEEN ''' +  @@PROCESS_DATE_FROM + ''' AND ''' + @@PROCESS_DATE_TO +'''';
END
ELSE IF(@@PROCESS_DATE_TO = '' AND @@PROCESS_DATE_FROM != '') BEGIN
	SET @@PROCESS_DATE_FROM = RIGHT(@@PROCESS_DATE_FROM, 4) + '-' + SUBSTRING(@@PROCESS_DATE_FROM, 4, 2) + '-' + LEFT(@@PROCESS_DATE_FROM, 2);
	SET @@QUERY = @@QUERY + ' AND CAST(PROCESS_START_DT AS DATE) = CAST(''' +  @@PROCESS_DATE_FROM + ''' AS DATE)';
	--SET @@QUERY = @@QUERY + ' AND CONVERT(VARCHAR, PROCESS_START_DT,104) = ''' + @@PROCESS_DATE_FROM + '''';
END




IF (@@LENGTH > 0) BEGIN
	SET @@QUERY = @@QUERY +  ' ORDER BY '+ @@ORDER_BY+ ' '+@@ORDER_TYPE+ ' OFFSET ' + CONVERT(VARCHAR, @@FROMNUMBER) + ' ROWS FETCH NEXT ' + CONVERT(VARCHAR, @@LENGTH) + ' ROWS ONLY';
END

EXECUTE (@@QUERY);