DECLARE 
	  @@QUERY VARCHAR(MAX)
	, @@PROCESS_DATE_FROM VARCHAR(50)
	, @@PROCESS_DATE_TO VARCHAR(50)
	, @@FUNCTION VARCHAR(50);
	
	SET @@PROCESS_DATE_FROM = REPLACE(@P_PROCESS_DATE_FROM, '''', '`');
	SET @@PROCESS_DATE_TO = REPLACE(@P_PROCESS_DATE_TO, '''', '`');
	SET @@FUNCTION		= REPLACE(@P_FUNCTION, '''', '`');;
	SET @@QUERY = '
		SELECT 
			COUNT(PROCESS_ID) AS CNT
		FROM 
			TB_R_LOG_H
		WHERE 1=1 ';


IF (@@FUNCTION != '') BEGIN
	SET @@QUERY = @@QUERY + ' AND FUNC_ID LIKE ''%' + CONVERT(VARCHAR, @@FUNCTION) + '%''';
END

IF (@@PROCESS_DATE_TO != '') BEGIN
	SET @@PROCESS_DATE_FROM = RIGHT(@@PROCESS_DATE_FROM, 4) + '-' + SUBSTRING(@@PROCESS_DATE_FROM, 4, 2) + '-' + LEFT(@@PROCESS_DATE_FROM, 2);
	SET @@PROCESS_DATE_TO = RIGHT(@@PROCESS_DATE_TO, 4) + '-' + SUBSTRING(@@PROCESS_DATE_TO, 4, 2) + '-' + LEFT(@@PROCESS_DATE_TO, 2);
	SET @@QUERY = @@QUERY + ' AND CAST(PROCESS_START_DT AS DATE) BETWEEN CAST(''' +  @@PROCESS_DATE_FROM + ''' AS DATE) AND CAST(''' + @@PROCESS_DATE_TO +''' AS DATE)';
	--SET @@QUERY = @@QUERY + ' AND CONVERT(VARCHAR, PROCESS_START_DT,104) BETWEEN ''' +  @@PROCESS_DATE_FROM + ''' AND ''' + @@PROCESS_DATE_TO +'''';
END
ELSE IF(@@PROCESS_DATE_TO = '' AND @@PROCESS_DATE_FROM != '') BEGIN
	SET @@PROCESS_DATE_FROM = RIGHT(@@PROCESS_DATE_FROM, 4) + '-' + SUBSTRING(@@PROCESS_DATE_FROM, 4, 2) + '-' + LEFT(@@PROCESS_DATE_FROM, 2);
	SET @@QUERY = @@QUERY + ' AND CAST(PROCESS_START_DT AS DATE) = CAST(''' +  @@PROCESS_DATE_FROM + ''' AS DATE)';
	--SET @@QUERY = @@QUERY + ' AND CONVERT(VARCHAR, PROCESS_START_DT,104) = ''' + @@PROCESS_DATE_FROM + '''';
END

EXECUTE (@@QUERY);