DECLARE 
	@@QUERY NVARCHAR(MAX),
	@@APP_ID NVARCHAR(MAX),
	@@MENU_ID NVARCHAR(MAX),
	@@MENU_PARENT NVARCHAR(MAX),
	@@P_START NVARCHAR(MAX),
	@@P_LENGTH NVARCHAR(MAX)

SET @@APP_ID = @APP_ID
SET @@MENU_ID = @P_MENU_ID
SET @@MENU_PARENT = @P_MENU_PARENT


SET @@QUERY = '
	SELECT 
		COUNT(*) AS CNT
	FROM 
		TB_M_MENU
	WHERE 1=1 '

IF (@@APP_ID != '') BEGIN
	SET @@QUERY = @@QUERY + ' AND APP_ID LIKE ''%' + @@APP_ID + '%''';
END

IF (@@MENU_ID != '') BEGIN
	SET @@QUERY = @@QUERY + ' AND MENU_ID LIKE ''%' + @@MENU_ID + '%''';
END

IF (@@MENU_PARENT != '') BEGIN
	SET @@QUERY = @@QUERY + ' AND MENU_PARENT LIKE ''%' + @@MENU_PARENT + '%''';
END

EXEC sp_executesql @@QUERY;
