DECLARE @@info VARCHAR(MAX);
DECLARE @@result VARCHAR(MAX);
DECLARE @@messages VARCHAR(MAX);


INSERT INTO TB_M_MENU (APP_ID, MENU_ID, MENU_PARENT, MENU_TEXT, MENU_TIPS, IS_ACTIVE, VISIBILITY, [URL], GLYPH, CREATED_BY, CREATED_DT, CHANGED_BY, SEPARATOR, [TARGET])
VALUES (@APP_ID, @APP_ID+''+@MENU_ID, @MENU_PARENT, @MENU_TEXT, @MENU_TIPS, @IS_ACTIVE, @VISIBILITY, @URL, @GLYPH, @CREATED_BY, GETDATE(), @CHANGED_BY, @SEPARATOR, @TARGET);

INSERT INTO TB_M_FUNCTION([APPLICATION],ID,[NAME],[DESCRIPTION],CREATED_BY,CREATED_DATE)
VALUES(@APP_ID, @APP_ID+''+@MENU_ID,@MENU_TEXT,@MENU_TIPS,@CREATED_BY, GETDATE())

SET @@info = 'success';
SET @@result = 'true';
SET @@messages = 'Data saved successfully';
select @@info as info, @@result as result, @@messages as messages;