DECLARE 
	  @@QUERY VARCHAR(MAX)
	, @@ID VARCHAR(MAX) = REPLACE(@P_ID, '''', '`')
	, @@NAME VARCHAR(MAX) = REPLACE(@P_NAME, '''', '`')
	, @@ROLE VARCHAR(MAX) = @P_ROLE
	, @@FUNCTION VARCHAR(MAX) = @P_FUNCTION
	, @@APPALIAS VARCHAR(MAX) = @P_APPALIAS;

	SET @@QUERY = '
		SELECT COUNT(*) AS CNT
		FROM (
			SELECT DISTINCT
					A.APPLICATION,
					ROLE,
					FEATURE as ID,
					B.NAME,
					B.DESCRIPTION
			 FROM TB_M_AUTHORIZATION A
			JOIN TB_M_FEATURE B ON A.FEATURE = B.ID AND B.APPLICATION = A.APPLICATION
			WHERE A.APPLICATION = '''+@@APPALIAS+'''
			AND A.ROLE = '''+@@ROLE+'''
			AND A.[FUNCTION] = '''+@@FUNCTION+'''
			AND A.FEATURE != ''''
		) AS distinct_rows';


IF (@@ID != '') BEGIN
	SET @@QUERY = @@QUERY + ' AND ID LIKE ''%' + @@ID + '%''';
END

IF (@@NAME != '') BEGIN
	SET @@QUERY = @@QUERY + ' AND B.NAME LIKE ''%' + @@NAME + '%''';
END

EXECUTE (@@QUERY);