DECLARE 
    @@QUERY VARCHAR(MAX), 
    @@NOREG VARCHAR(MAX) = @P_NOREG,
    @@BASE_URL VARCHAR(MAX) ;

SET  @@BASE_URL = (
    SELECT SYSTEM_VALUE
    from DBO.TB_M_SYSTEM
    WHERE 
    FUNCTION_ID = 'ENVIRONMENT_PDI' 
    AND SYSTEM_CD = 'URL_BACKEND'	
);

SET @@QUERY = ' 
SELECT 
    B.LANGUAGE_ID ,
    B.LANGUAGE_NAME ,
    PH.NAME AS EMPLOYEE_NAME,
    C.SKILL_DESC ,
    A.SKILL_LEVEL ,
    A.NOREG,
    A.CERTIFICATE_NAME ,
    A.CERTIFICATE_PATH ,
    A.SCORE ,
    A.LANGUAGE_TEST ,
    A.VALID_TO ,
    A.REMARK_1 ,
    A.CREATED_BY ,
    A.CREATED_DT        
FROM PDI.TB_M_PROFILE_LANGUAGE A
JOIN PDI.TB_M_LANGUAGE B ON B.LANGUAGE_ID=A.LANGUAGE_ID
JOIN PDI.TB_M_LANGUAGE_SKILL C ON C.SKILL_LEVEL=A.SKILL_LEVEL
LEFT JOIN DBO.TB_M_PROFILE_HEADER PH ON A.NOREG=PH.NOREG
WHERE 1=1
AND A.NOREG IN ( '+@@NOREG+' )
ORDER BY A.NOREG ASC, A.VALID_TO DESC
';


EXECUTE (@@QUERY);
