DECLARE 
	@@QUERY NVARCHAR(MAX),
	@@R_SUBMISSION_ID INT = @P_R_SUBMISSION_ID;

SET @@QUERY = N'
SELECT 
	*
FROM 
	ASP.TB_R_SUBMISSION_ANSWER AS A
WHERE
	A.R_SUBMISSION_ID = @@SUBMISSION_ID
';

EXEC sp_executesql @@QUERY,  N'@@SUBMISSION_ID INT', @@SUBMISSION_ID = @@R_SUBMISSION_ID;