DECLARE 
	@@QUERY NVARCHAR(MAX),
	@@NOREG VARCHAR(20) = @P_NOREG,
	@@M_PERIODE_ID INT = @P_M_PERIODE_ID,
	@@M_QUESTION_ID INT = @P_M_QUESTION_ID;

SET @@QUERY = N'
SELECT 
    B.ANSWER,
    B.ANSWER_TEXT
FROM 
	ASP.TB_R_ANSWER A
LEFT JOIN 
		ASP.TB_R_ANSWER_DETAIL B
	ON
		B.R_ANSWER_ID  = A.R_ANSWER_ID
WHERE
	A.NOREG = @@NOREG
	AND A.M_PERIODE_ID = @@PERIODE_ID
	AND A.M_QUESTION_ID = @@QUESTION_ID
';

EXEC sp_executesql @@QUERY,  N'@@NOREG VARCHAR(20), @@PERIODE_ID INT, @@QUESTION_ID INT', @@NOREG = @@NOREG, @@PERIODE_ID = @@M_PERIODE_ID, @@QUESTION_ID = @@M_QUESTION_ID;