DECLARE 
	@@QUERY NVARCHAR(MAX)
	, @@QUESTION_ID INT = @P_M_QUESTION_ID
	, @@PERIODE_ID  INT = @P_M_PERIODE_ID
	, @@RECENT_DATA BIT = @P_RECENT_DATA
	, @@TABLE_OPTION NVARCHAR(128)
	, @@TABLE_OPTION_DETAIL NVARCHAR(128)
	, @@CONDITIONAL_JOIN_TB_OPTION_DETAIL_TO_TB_OPTION NVARCHAR(128);

IF(@@RECENT_DATA = 1) BEGIN 
	SET @@TABLE_OPTION = 'ASP.TB_M_OPTION';
	SET @@TABLE_OPTION_DETAIL = 'ASP.TB_M_OPTION_DETAIL';
	SET @@CONDITIONAL_JOIN_TB_OPTION_DETAIL_TO_TB_OPTION = 'B.M_OPTION_ID = A.M_OPTION_ID';
END ELSE BEGIN
	SET @@TABLE_OPTION = 'ASP.TB_M_PERIODE_OPTION';
	SET @@TABLE_OPTION_DETAIL = 'ASP.TB_M_PERIODE_OPTION_DETAIL';
	SET @@CONDITIONAL_JOIN_TB_OPTION_DETAIL_TO_TB_OPTION = 'B.M_OPTION_ID = A.M_OPTION_ID AND B.M_PERIODE_ID = @@PERIODE_ID';
END

-- GET QUESTION BY CATEGORY
SET @@QUERY = N'
SELECT 
	B.M_OPTION_DETAIL_ID AS ID,
	B.OPTION_DETAIL_DESC AS "DESC"
FROM 
	' + @@TABLE_OPTION + ' A
JOIN 
	' + @@TABLE_OPTION_DETAIL + ' B ON ' + @@CONDITIONAL_JOIN_TB_OPTION_DETAIL_TO_TB_OPTION + '
WHERE
	B.IS_ACTIVE = 1
';

IF(@@RECENT_DATA = 0) BEGIN 
	SET @@QUERY = @@QUERY + N' AND A.M_PERIODE_ID = @@PERIODE_ID';
END

IF(@@QUESTION_ID IS NOT NULL) BEGIN 
	SET @@QUERY = @@QUERY + N' AND A.M_QUESTION_ID = @@QUESTION_ID';
END 

SET @@QUERY = @@QUERY + N' ORDER BY B.OPTION_DETAIL_ORDER ASC';

EXEC sp_executesql @@QUERY,  N' @@PERIODE_ID INT, @@QUESTION_ID INT', @@PERIODE_ID = @@PERIODE_ID, @@QUESTION_ID = @@QUESTION_ID;