DECLARE 
	@@QUERY NVARCHAR(MAX),
	@@M_PERIODE_ID INT = @P_M_PERIODE_ID,
	@@NOREG VARCHAR(30) = @P_NOREG;

SET @@QUERY = N'
SELECT 
	*
FROM 
	ASP.TB_R_ANSWER AS A
WHERE
		A.M_PERIODE_ID = @@PERIODE_ID
	AND
		A.NOREG = @@NOREG
';

EXEC sp_executesql @@QUERY,  N'@@PERIODE_ID INT, @@NOREG VARCHAR(30)', @@PERIODE_ID = @@M_PERIODE_ID, @@NOREG = @@NOREG;