DECLARE 
	@@QUERY NVARCHAR(MAX),
	@@M_PERIODE_ID INT = @P_M_PERIODE_ID;

SET @@QUERY = N'
SELECT 
	A.M_PERIODE_ID 
FROM 
	ASP.TB_M_PERIODE AS A
WHERE 
	GETDATE() BETWEEN A.PERIODE_START AND A.PERIODE_END
';

IF(@@M_PERIODE_ID IS NOT NULL) BEGIN 
	SET @@QUERY = @@QUERY + N' AND A.M_PERIODE_ID = @@PERIODE_ID';
END 

EXEC sp_executesql @@QUERY,  N'@@PERIODE_ID INT', @@PERIODE_ID = @@M_PERIODE_ID;