DECLARE 
    @@QUERY VARCHAR(MAX), 
    @@QUERY_REQ VARCHAR(MAX),
    @@QUERY_CTE VARCHAR(MAX),
    @@NOREG VARCHAR(MAX) = @P_NOREG,
    @@ORDER_TYPE VARCHAR(MAX) = REPLACE(@P_ORDER_TYPE, '''', '`'),
    @@REQ_STATUS VARCHAR(MAX) = @P_STATUS;
	
	

SET @@QUERY = '
SELECT
SQ.*,
C.COUNTRY_NAME,
SH.PERSONNEL_NAME AS APP_SH_NAME,
STAT_SH.SYSTEM_VALUE AS APP_SH_LABEL,
DPH.PERSONNEL_NAME AS APP_DPH_NAME,
STAT_DPH.SYSTEM_VALUE AS APP_DPH_LABEL,
DH.PERSONNEL_NAME AS APP_DH_NAME,
STAT_DH.SYSTEM_VALUE AS APP_DH_LABEL,
DIR.PERSONNEL_NAME AS APP_DIR_NAME,
STAT_DIR.SYSTEM_VALUE AS APP_DIR_LABEL,
HR.PERSONNEL_NAME AS APP_HR_NAME,
STAT_HR.SYSTEM_VALUE AS APP_HR_LABEL
FROM (
    SELECT
	    B.TRANSACTION_ID,
        IIF(B.TRANSACTION_ID IS NULL, A.NOREG, B.NOREG) AS NOREG,
        IIF(B.TRANSACTION_ID IS NULL, A.HOST_COMPANY, B.HOST_COMPANY) AS HOST_COMPANY,
        IIF(B.TRANSACTION_ID IS NULL, A.HOST_COUNTRY, B.HOST_COUNTRY) AS HOST_COUNTRY,
        FORMAT(IIF(B.TRANSACTION_ID IS NULL, A.PERIODE_FROM, B.PERIODE_FROM), ''yyyy-MM-dd'') AS PERIODE_FROM,
        FORMAT(IIF(B.TRANSACTION_ID IS NULL, A.PERIODE_TO, B.PERIODE_TO), ''yyyy-MM-dd'') AS PERIODE_TO,
        IIF(B.TRANSACTION_ID IS NULL, A.HOST_DIVISION, B.HOST_DIVISION) AS HOST_DIVISION,
        IIF(B.TRANSACTION_ID IS NULL, A.HOST_DEPARTMENT, B.HOST_DEPARTMENT) AS HOST_DEPARTMENT,
        IIF(B.TRANSACTION_ID IS NULL, A.HOST_SECTION, B.HOST_SECTION) AS HOST_SECTION,
        IIF(B.TRANSACTION_ID IS NULL, A.RESPONSIBILITY, B.RESPONSIBILITY) AS RESPONSIBILITY,
        IIF(B.TRANSACTION_ID IS NULL, A.ACCOMPLISHMENT, B.ACCOMPLISHMENT) AS ACCOMPLISHMENT,
        IIF(B.TRANSACTION_ID IS NULL, A.HOST_CLASS, B.HOST_CLASS) AS HOST_CLASS,
        IIF(B.TRANSACTION_ID IS NULL, A.HOST_POSITION, B.HOST_POSITION) AS HOST_POSITION,
        B.STATUS_CD,
        B.REJECT_REASON,
        B.APP_SH_NOREG,
        B.APP_SH_STATUS,
        B.APP_SH_DATE,
        B.APP_DPH_NOREG,
        B.APP_DPH_STATUS,
        B.APP_DPH_DATE,
        B.APP_DH_NOREG,
        B.APP_DH_STATUS,
        B.APP_DH_DATE,
        B.APP_DIR_NOREG,
        B.APP_DIR_STATUS,
        B.APP_DIR_DATE,
        B.APP_HR_ADMIN_NOREG,
        B.APP_HR_ADMIN_STATUS,
        B.APP_HR_ADMIN_DATE,
        B.CANCEL_FLAG,
        B.CANCEL_BY,
        B.CANCEL_DATE,
        A.REMARK_1 AS REMARK_1,
        A.REMARK_2 AS REMARK_2
    FROM PDI.TB_M_PROFILE_ICT_HISTORY A
    LEFT JOIN PDI.TB_R_SUBMISSION_ICT_HISTORY B 
        ON A.NOREG = B.NOREG 
        AND A.HOST_COMPANY = B.HOST_COMPANY  
        AND A.PERIODE_FROM = B.PERIODE_FROM 
        AND A.PERIODE_TO = B.PERIODE_TO 
        AND B.CANCEL_FLAG IS NULL 
        AND B.STATUS_CD != ''99'' 
    WHERE A.NOREG = '''+@@NOREG+''' 
    UNION
    SELECT
		B.TRANSACTION_ID,
        B.NOREG,
        B.HOST_COMPANY,
        B.HOST_COUNTRY,
        FORMAT(B.PERIODE_FROM, ''yyyy-MM-dd'') AS PERIODE_FROM,
        FORMAT(B.PERIODE_TO, ''yyyy-MM-dd'') AS PERIODE_TO,
        B.HOST_DIVISION,
        B.HOST_DEPARTMENT,
        B.HOST_SECTION,
        B.RESPONSIBILITY,
        B.ACCOMPLISHMENT,
        B.HOST_CLASS,
        B.HOST_POSITION,
        B.STATUS_CD,
        B.REJECT_REASON,
        B.APP_SH_NOREG,
        B.APP_SH_STATUS,
        B.APP_SH_DATE,
        B.APP_DPH_NOREG,
        B.APP_DPH_STATUS,
        B.APP_DPH_DATE,
        B.APP_DH_NOREG,
        B.APP_DH_STATUS,
        B.APP_DH_DATE,
        B.APP_DIR_NOREG,
        B.APP_DIR_STATUS,
        B.APP_DIR_DATE,
        B.APP_HR_ADMIN_NOREG,
        B.APP_HR_ADMIN_STATUS,
        B.APP_HR_ADMIN_DATE,
        B.CANCEL_FLAG,
        B.CANCEL_BY,
        B.CANCEL_DATE,
        NULL AS REMARK_1,
        NULL AS REMARK_2
    FROM PDI.TB_R_SUBMISSION_ICT_HISTORY B
    WHERE B.NOREG = '''+@@NOREG+'''
    AND B.CANCEL_FLAG IS NULL
    AND B.STATUS_CD != 99
) SQ
LEFT JOIN DBO.TB_M_COUNTRY C ON SQ.HOST_COUNTRY=C.COUNTRY_CD
LEFT JOIN (SELECT DISTINCT(SUB_A.NOREG), SUB_A.PERSONNEL_NAME from VW_ORGANIZATION SUB_A) SH ON SH.NOREG = SQ.APP_SH_NOREG AND SQ.APP_SH_NOREG IS NOT NULL 
LEFT JOIN (SELECT DISTINCT(SUB_A.NOREG), SUB_A.PERSONNEL_NAME from VW_ORGANIZATION SUB_A) DPH ON DPH.NOREG=SQ.APP_DPH_NOREG AND SQ.APP_DPH_NOREG IS NOT NULL 
LEFT JOIN (SELECT DISTINCT(SUB_A.NOREG), SUB_A.PERSONNEL_NAME from VW_ORGANIZATION SUB_A) DH ON DH.NOREG=SQ.APP_DH_NOREG AND SQ.APP_DH_NOREG IS NOT NULL 
LEFT JOIN (SELECT DISTINCT(SUB_A.NOREG), SUB_A.PERSONNEL_NAME from VW_ORGANIZATION SUB_A) DIR ON DIR.NOREG=SQ.APP_DIR_NOREG AND SQ.APP_DIR_NOREG IS NOT NULL 
LEFT JOIN (SELECT DISTINCT(SUB_A.NOREG), SUB_A.PERSONNEL_NAME from VW_ORGANIZATION SUB_A) HR ON HR.NOREG=SQ.APP_HR_ADMIN_NOREG AND SQ.APP_HR_ADMIN_NOREG IS NOT NULL
LEFT JOIN dbo.TB_M_SYSTEM STAT_SH ON SQ.APP_SH_STATUS IS NOT NULL AND STAT_SH.FUNCTION_ID=''STATUS_APPROVAL_PDI'' AND SQ.APP_SH_STATUS = STAT_SH.SYSTEM_CD
LEFT JOIN dbo.TB_M_SYSTEM STAT_DPH ON SQ.APP_DPH_STATUS IS NOT NULL AND STAT_DPH.FUNCTION_ID=''STATUS_APPROVAL_PDI'' AND SQ.APP_DPH_STATUS = STAT_DPH.SYSTEM_CD
LEFT JOIN dbo.TB_M_SYSTEM STAT_DH ON SQ.APP_DH_STATUS IS NOT NULL AND STAT_DH.FUNCTION_ID=''STATUS_APPROVAL_PDI'' AND SQ.APP_DH_STATUS = STAT_DH.SYSTEM_CD
LEFT JOIN dbo.TB_M_SYSTEM STAT_DIR ON SQ.APP_DIR_STATUS IS NOT NULL AND STAT_DIR.FUNCTION_ID=''STATUS_APPROVAL_PDI'' AND SQ.APP_DIR_STATUS = STAT_DIR.SYSTEM_CD
LEFT JOIN dbo.TB_M_SYSTEM STAT_HR ON SQ.APP_HR_ADMIN_STATUS IS NOT NULL AND STAT_HR.FUNCTION_ID=''STATUS_APPROVAL_PDI'' AND SQ.APP_HR_ADMIN_STATUS = STAT_HR.SYSTEM_CD

---
WHERE 
    1=1 
ORDER BY SQ.PERIODE_TO DESC
';

EXECUTE (@@QUERY)