DECLARE   
    @@QUERY VARCHAR(MAX), 
    @@NOREG VARCHAR(MAX) = @P_NOREG
    ;

 

SET @@QUERY = '
SELECT
A.NOREG ,
    PH.NAME AS EMPLOYEE_NAME,
A.HOST_CLASS ,
A.HOST_COMPANY ,
A.HOST_COUNTRY ,
A.HOST_DEPARTMENT ,
A.HOST_DIVISION ,
A.HOST_POSITION ,
A.HOST_SECTION ,
A.ACCOMPLISHMENT ,
A.RESPONSIBILITY ,
A.REMARK_1 ,
CONVERT(varchar(10), A.PERIODE_FROM, 120) AS PERIODE_FROM ,
CONVERT(varchar(10), A.PERIODE_TO, 120) AS PERIODE_TO ,
B.COUNTRY_NAME ,
A.CREATED_DT ,
A.CREATED_BY
FROM PDI.TB_M_PROFILE_ICT_HISTORY A
LEFT JOIN DBO.TB_M_COUNTRY B ON A.HOST_COUNTRY=B.COUNTRY_CD 
LEFT JOIN DBO.TB_M_PROFILE_HEADER PH ON A.NOREG=PH.NOREG
WHERE 1=1 AND A.NOREG IN ( '+@@NOREG+' ) 
ORDER BY A.NOREG ASC, A.PERIODE_TO DESC
';


EXECUTE (@@QUERY);