DECLARE 
    @@QUERY VARCHAR(MAX), 
    @@NOREG VARCHAR(MAX) = @P_NOREG,
    @@BASE_URL VARCHAR(MAX);

    
      
SET  @@BASE_URL = (
    SELECT SYSTEM_VALUE
    from DBO.TB_M_SYSTEM
    WHERE 
    FUNCTION_ID = 'ENVIRONMENT_PDI' 
    AND SYSTEM_CD = 'URL_BACKEND'	
);
 
SET @@QUERY = '
SELECT
A.NOREG ,
    PH.NAME AS EMPLOYEE_NAME,
A.SEQ ,
A.TRAINING_TYPE ,
a.TRAINING_TOPIC ,
A.INSTITUTION ,
A.COUNTRY_ID ,
B.COUNTRY_NAME ,
A.YEAR ,
A.SKILL ,
A.CERTIFICATE_NAME ,
CONCAT('''+@@BASE_URL+''', A.CERTIFICATE_PATH)  AS CERTIFICATE_PATH ,
A.REMARK_1 AS REMARK_1 ,
A.REMARK_2 AS REMARK_2 ,
A.CREATED_DT ,
A.CREATED_BY
FROM PDI.TB_M_PROFILE_TRAINING_HISTORY A
LEFT JOIN DBO.TB_M_COUNTRY B ON A.COUNTRY_ID=B.COUNTRY_CD
LEFT JOIN DBO.TB_M_PROFILE_HEADER PH ON A.NOREG=PH.NOREG
WHERE 1=1 
AND A.TRAINING_TYPE = 2
AND A.NOREG IN ( '+@@NOREG+' ) 
ORDER BY A.NOREG ASC, A.YEAR DESC
';

EXECUTE (@@QUERY);