DECLARE @@QUERY VARCHAR(MAX) ;
DECLARE @@EDUCATION_CD VARCHAR(MAX) = @P_EDUCATION_CD;

SET @@QUERY = 'SELECT * FROM PDI.TB_M_EDUCATION_MAJOR WHERE 1=1 ';

IF(@@EDUCATION_CD != '') BEGIN 
    SET @@QUERY = @@QUERY + ' AND EDUCATION_CD LIKE ''%'+@@EDUCATION_CD+'%'' ';
END;

EXECUTE (@@QUERY);  
-- * FROM PDI.TB_M_EDUCATION WHERE EDUCATION_CD=